<?php

/*
 * This file is licensed under GPLv2+.
 */

/**
 * @file
 * Defines the basic information of certificate.
 */
 
/**
 * Implementation of hook_help().
 */
function certificate_help($path, $arg) {
	switch ($path) {
		case 'certificate':
			$output = t('You may administrate various basic information of certificates via following features.');
			break;
		case 'certificate/specification':
			$output = t('In this page, you could modify or add new certificate specification.');
			break;
		case 'certificate/preload':
			$output = t('In this page, you could preload certificates already issued, for students to claim.');
			break;
	}
	if (isset($output))
		return $output;
}

/**
 * Implementation of hook_permission().
 */
function certificate_permission() {
	return array(
		'admin certificates' => array(
			'title' => t('Administrate certificates types'),
		),
	);
}

/**
 * Implementation of hook_theme().
 */
function certificate_theme() {
	return array(
		'certificate_specification_form' => array(
			'render element' => 'form', 
		),
	);
}

/**
 * Implementation of hook_menu().
 */
function certificate_menu() {
	$items=array();
	$items['certificate']=array(
		'title' => 'Certificates Management',
		'description' => "Manage the certificates",
		'page callback' => 'certificate_blocklist',
		'weight' => 7,
		'access callback' => 'user_access',
		'access arguments'=> array('admin certificates'),
		'expanded' => TRUE,
	);
	$items['certificate/specification']=array(
		'title' => 'Specification Management',
		'weight' => '1',
		'description' => "Manage the specifications",
		'page callback' => 'drupal_get_form',
		'page arguments' => array('certificate_specification_form'),
		'access callback' => 'user_access',
		'access arguments'=> array('admin certificates'),
	);
	$items['certificate/operations']=array(
		'title' => 'Operations Management',
		'weight' => 2,
		'description' => "Manage the operations",
		'page callback' => 'drupal_get_form',
		'page arguments' => array('certificate_operations_form'),
		'access callback' => 'user_access',
		'access arguments'=> array('admin certificates'),
	);
	return $items;
}

/**
 * Provide a single block from the administration menu as a page.
 * This function is often a destination for these blocks.
 * For example, 'admin/content/types' needs to have a destination to be valid
 * in the Drupal menu system, but too much information there might be
 * hidden, so we supply the contents of the block.
 *
 * @return
 *   The output HTML.
 */
function certificate_blocklist() {
	$item = menu_get_item();
	$content = system_admin_menu_block($item);

	return theme('admin_block_content', array('content' => $content));
}

/**
 * Callback function of 'certificate/specification'
 */
function certificate_specification_form($form, $form_state) {
	$form=array();
	if(isset($form_state['storage']['cid'])) {
		$form['cid']=array('#type'=>'hidden','#value'=>$form_state['storage']['cid']);
		$certificate=db_query('SELECT * FROM {certificates} WHERE cid=:cid',array(':cid'=>$form_state['storage']['cid']))->fetchObject();
	} else $certificate=FALSE;

	$form['#attached']['css']=array(
		'.inline-element-div label, .inline-element-div select, .inline-element-div input, .inline-element-div div.form-item { display: inline; }' => array('type'=>'inline')
	);

	$form['addnotice']=array(
		'#markup' => '<strong>'.($certificate?t('Modify specification'):t('Add specification')).'</strong>',
	);

	$series=array();
	$dbo=db_query('SELECT DISTINCT series FROM {certificates}');
	$i=1;
	$c_series=1;
	foreach($dbo as $r) {
		$series+=array($i=>$r->series);
		if($certificate&&$r->series==$certificate->series) $c_series=$i;
		$i++;
	}
	$form['begin']=array(
		'#markup' => '<div class="inline-element-div">',
	);
	if($i>1) {
		$form['series_caption']=array(
			'#type' => 'item',
			'#title' => t('Series'),
			'#required' => TRUE,
		);
		$series+=array('0'=>t('-- New series --'));
		$form['series']=array(
			'#type' => 'select',
			'#required' => TRUE,
			'#default_value' => 1,
			'#options' => $series,
		);
		$form['series_input']=array(
			'#type' => 'textfield',
			'#title' => t(', in the name of'),
			'#title_display' => 'before',
			'#maxlength' => 30,
			'#size' => 30,
			'#states' => array(
				'visible' => array(
					':input[name="series"]' => array('value' =>'0'),
				),
				'required' => array(
					':input[name="series"]' => array('value' =>'0'),
				),
			),
		);
		$form['#attached']['js'][]=array('data'=>
			'jQuery(document).ready(function(){'.
				'jQuery("#edit-series").change(function(){ '.
				'if(jQuery("#edit-series").val()==0) {'.
					'jQuery("#edit-series-input").val(""); }'.
				'else {'.
					'jQuery("#edit-series-input").val(jQuery("#edit-series").find("option:selected").text());'.
					'}'.
				'});'. // end series.change function()
				'});'. // end document ready function()
				'','type' => 'inline'
		);
	}
	else {
		$form['series']=array(
			'#type' => 'hidden',
			'#value' => '0',
		);
		$form['series_input']=array(
			'#type' => 'textfield',
			'#title' => t('Series Name'),
			'#maxlength' => 30,
			'#size' => 40,
			'#required' => TRUE,
		);
	}
	$form['name']=array(
		'#type' => 'textfield',
		'#title' => t('Specification Name'),
		'#required' => TRUE,
		'#maxlength' => 50,
		'#size' => 40,
	);
	$form['end']=array(
		'#markup' => '</div>'
	);
	$form['c_series']=array('#type'=>'hidden','#value'=>$c_series);
	$form['c_name']=array('#type'=>'hidden','#value'=>$certificate?$certificate->name:'');
	$form['#attached']['js'][]= array('data'=>
		'jQuery(document).ready(function(){'.
			'if(jQuery(":input[name=\"c_series\"]").val()!="") jQuery("#edit-series").val(jQuery(":input[name=\"c_series\"]").val());'.
			'else jQuery("#edit-series").val("0");'.
			'jQuery("#edit-name").val(jQuery(":input[name=\"c_name\"]").val());'.
			'jQuery("#edit-series").change();'.
			'});'.
			'', 'type'=>'inline'
	);
	$form['save']=array(
		'#type' => 'submit',
		'#name' => 'save',
		'#value' => t('Save'),
	);

	$form['existingnotice']=array(
		'#markup' => '<div style="margin-top: 20px;"><strong>'.t('Existing specifications').'</strong></div>',
	);
	$header=array(
		'series' => array('data' => t('Series'), 'field'=> 'series'),
		'name' => array('data' => t('Specification'), 'field'=> 'name'),
	);
	
	$query=db_select('certificates','c')->fields('c')
		->extend('TableSort')->orderByHeader($header)->extend('PagerDefault')->limit(20);
	$result=$query->execute();
	$form['existing']=array('#type'=>'fieldset');

	foreach($result as $r) {
		$form['existing']['cid'.$r->cid]=array('#type'=>'hidden','#value'=>$r->cid);
		$form['existing']['series'.$r->cid]=array('#markup'=>$r->series);
		$form['existing']['name'.$r->cid]=array('#markup'=>$r->name);
		$form['existing']['modify'.$r->cid]=array('#type'=>'submit','#submit'=>array('certificate_specification_form_modify_submit'),'#limit_validation_errors'=>array(),'#name'=>'modify_'.$r->cid,'#value'=>t('Modify'));
		$form['existing']['delete'.$r->cid]=array('#type'=>'submit','#submit'=>array('certificate_specification_form_delete_submit'),'#limit_validation_errors'=>array(),'#name'=>'delete_'.$r->cid,'#value'=>t('Delete'));
	}
	return $form;
}

function certificate_specification_form_validate($form, $form_state) {
	if($form_state['values']['series']=='0' && trim($form_state['values']['series_input'])==FALSE)
		form_set_error('series_input', t('Series name is required.'));
}

function certificate_specification_form_submit($form, $form_state) {
	// if cid is not set, then add new specification
	if(!isset($form_state['storage']['cid'])) {
		$i=db_query('SELECT MAX(cid) FROM {certificates}')->fetchField();
		db_insert('certificates')->fields(array(
			'cid' => $i+1,
			'series' => $form_state['values']['series_input'],
			'name' => $form_state['values']['name'],
		))->execute();
		drupal_set_message(t('Specification added.'));
	} else {
		db_update('certificates')->fields(array(
			'series' => $form_state['values']['series_input'],
			'name' => $form_state['values']['name'],
		))->condition('cid',$form_state['storage']['cid'])->execute();
		drupal_set_message(t('Specification Saved.'));
	}
}

function certificate_specification_form_modify_submit($form, &$form_state) {
	$form_state['rebuild'] = TRUE;
	$form_state['storage']['cid']=substr($form_state['triggering_element']['#name'],7);
}

function certificate_specification_form_delete_submit($form, $form_state) {
	db_delete('certificates')->condition('cid',substr($form_state['triggering_element']['#name'],7))->execute();
	drupal_set_message(t('Specification Deleted.'));
}

function theme_certificate_specification_form($variables) {
	$form=$variables['form'];
	$output ='';
	$output.=drupal_render($form['addnotice']);
	$output.=drupal_render($form['series_caption']);
	$output.=drupal_render($form['series']);
	$output.=drupal_render($form['series_input']);
	$output.=drupal_render($form['end']);
	$output.=drupal_render($form['name']);
	$output.=drupal_render($form['save']);
	$output.=drupal_render($form['existingnotice']);
	$rows=array();
	foreach($form['existing'] as $key=>$val) {
		//var_dump($key);
		if(substr($key,0,3)!='cid') continue;
		$cid=substr($key,3);
		if(isset($form['cid']) && $form['cid']['#value']==$cid) {
			$rows[]=array(
				'data'=>array(
					drupal_render($form['existing']['series'.$cid]),
					drupal_render($form['existing']['name'.$cid]),
					t('Now Editing'),
				),
				'class'=>array('rowselected'),
			);
			unset($form['existing']['modify'.$cid]);
			unset($form['existing']['delete'.$cid]);
		} else {
			$rows[]=array(
				drupal_render($form['existing']['series'.$cid]),
				drupal_render($form['existing']['name'.$cid]),
				drupal_render($form['existing']['modify'.$cid]).drupal_render($form['existing']['delete'.$cid]),
			);
		}
	}
	$header=array(
		'series' => array('data' => t('Series'), 'field'=> 'series'),
		'name' => array('data' => t('Specification'), 'field'=> 'name'),
		'modify' => array('data' => t('Operations')),
	);
	$output.=theme('table', array('header'=>$header, 'rows'=>$rows, 'empty'=>t('No existing specifications.')));
	unset($form['existing']);
	$output.=drupal_render_children($form);
	$output .= theme('pager');
	return $output;
}

function certificate_operations_form($form, $form_state) {
	if(empty($form)) $form=array();
	if(!isset($form_state['storage']['operation'])) $form_state['storage']['operation']='0';
	$form['#attached']['css']=array(
		'.inline-element-div label, .inline-element-div select, .inline-element-div input, .inline-element-div div.form-item { display: inline; }' => array('type'=>'inline')
	);
	$query=db_query('SELECT o.oid, o.name as oname FROM {operations} o WHERE EXISTS(SELECT * FROM {certificates_operations} co WHERE co.oid=o.oid)');
	$options=array(
		'0' => t('All operations'),
	);
	foreach($query as $r) {
		$options+=array(
			$r->oid => $r->oname
		);
	}
	$form['operation']=array(
		'#type' => 'select',
		'#title' => t('Select Operation'),
		'#options' => $options,
		'#prefix' => '<div class="inline-element-div">',
		'#default_value' => $form_state['storage']['operation'],
	);
	$form['refresh']=array(
		'#type' => 'submit',
		'#value' => t('Refresh'),
		'#suffix' => '</div>',
		'#limit_validation_errors' => array(),
		'#submit' => array('certificate_operations_form_refresh_submit')
	);
	$rdbo=db_query('SELECT * FROM {certificates} ORDER by cid');
	$certs=array();
	foreach($rdbo as $r) {
		$certs[$r->cid]=array('series'=>$r->series, 'name'=>$r->name);
	}
	$rdbo=db_query('SELECT DISTINCT o.name AS oname, c.cid, c.name AS cname, c.series AS series '.
		'FROM {certificates_operations} co INNER JOIN {operations} o ON co.oid=o.oid '.
		'INNER JOIN {certificates} c ON co.cid=c.cid ORDER BY co.oid DESC, co.cid');
	$operations=array();
	if($form_state['storage']['operation']=='0')
		$header=array(
			'oid'=>array('data'=>t('Running Operations'), 'field'=>'oid', 'sort'=>'desc'),
			'cnames'=>t('Valid certificates'),
		);
	else $header=array('cnames'=>t('Valid certificates'));
	$query=db_select('operations','o')->fields('o',array('oid'));
	$query->addExpression('o.name','oname');
	$subquery=db_select('certificates_operations','co')->fields('co')->where('co.oid=o.oid');
	$query->exists($subquery);
	if($form_state['storage']['operation']!='0')
		$query->condition('o.oid',$form_state['storage']['operation']);
	else 
		$query=$query->extend('PagerDefault')->limit(10)->extend('TableSort')->orderByHeader($header);
	$rdbo=$query->execute();
	$rows=array();
	foreach($rdbo as $r) {
		$dbo=db_query('SELECT DISTINCT co.oid, c.name AS cname, c.series AS series '.
			'FROM {certificates_operations} co INNER JOIN {operations} o ON co.oid=o.oid '.
			'INNER JOIN {certificates} c ON co.cid=c.cid WHERE co.oid=:oid ORDER BY co.oid DESC, co.cid',
			array(':oid'=>$r->oid));
		$certs=array();
		foreach($dbo as $db) {
			$certs[$db->series][]=$db->cname;
		}
		foreach($certs as $series=>$cnames) {
			$certificates=sprintf('%s<ul><li>%s</li></ul>', $series, implode($cnames,'</li><li>'));
		}
		if($form_state['storage']['operation']=='0')
			$rows[$r->oid]=array(
				'oid'=>$r->oname,
				'cnames'=>$certificates
			);
		else {
			if(count($certs[$series])>1)
				$rows[$r->oid]=array('cnames'=>sprintf('<ul><li>%s</li></ul>', implode($certs[$series],'</li><li>')));
			else
				$rows[$r->oid]=array('cnames'=>$certs[$series][0]);
		}
	}
	if($form_state['storage']['operation']=='0') {
		$form['cert_operations']=array(
			'#type' =>'tableselect',
			'#multiple' => FALSE,
			'#header'=>$header,
			'#options'=>$rows,
			'#empty'=>t('No existing operations'),
			'#suffix' => theme('pager'),
		);
	}
	else  {
		$form['cert_operations']=array(
			'#type' =>'markup',
			'#markup' => theme('table', array('header' => $header, 'rows'=>$rows))
		);
	}
	if(date('m')>'06') {
		$options=array(
			sprintf("%4d%2d",(int)date('Y')+1,'02') => t('!year winter', array('!year'=>(int)date('Y')+1)),
			sprintf("%4d%2d",(int)date('Y')+1,'08') => t('!year summer', array('!year'=>(int)date('Y')+1)),
		);
	} else {
		$options=array(
			sprintf("%4d%2d",(int)date('Y'),'08') => t('!year summer', array('!year'=>(int)date('Y'))),
			sprintf("%4d%2d",(int)date('Y')+1,'02') => t('!year winter', array('!year'=>(int)date('Y')+1)),
		);
	}
	if(!empty($rows)) {
		$options+=array('0000'=>t('New date'));
		$form['copyoperationselectyear']=array(
			'#type' => 'select',
			'#prefix' => '<div class="inline-element-div">'.t('Copy selected operation into'),
			'#options' => array(
				date('Y') => date('Y').t('Year'),
				date('Y')+1 => (date('Y')+1).t('Year')
			),
			'#required' => TRUE,
		);
		$options=array(
			'02' => t('Feb (winter)'),
			'08' => t('Aug (summer)'),
			'01' => t('Jan'),
			'03' => t('Mar'),
			'04' => t('Apr'),
			'05' => t('May'),
			'06' => t('Jun'),
			'07' => t('Jul'),
			'09' => t('Sep'),
			'10' => t('Oct'),
			'11' => t('Nov'),
			'12' => t('Dec'),
		);
		$form['copyoperationselectmonth']=array(
			'#type' => 'select',
			'#title' => t('Month select'),
			'#title_display' => 'invisible',
			'#options' => $options,
			'#required' => TRUE,
		);
		$form['copyexecute']=array(
			'#type' => 'submit',
			'#value' => t('Copy and Generate new operation'),
			'#suffix' => '</div>',
		);
	}
	return $form;
}

function certificate_operations_form_refresh_submit($form, &$form_state) {
	$form_state['storage']['operation']=$_POST['operation'];
	$form_state['rebuild']=TRUE;
}

function certificate_operations_load($cid, $oid) {
	$query=db_query('SELECT co.*, c.name AS cname, o.name as oname, c.series FROM {certificates_operations} co '.
		'INNER JOIN {operations} o ON o.oid=co.oid '.
		'INNER JOIN {certificates} c ON c.cid=co.cid '.
		'WHERE co.cid=:cid AND co.oid=:oid',
		array(':cid'=>$cid, ':oid'=>$oid)
	);
	return $query->fetchObject();
}

?>
