<?php

/*
 * This file is licensed under GPLv2+.
*/

function _cert_issue_get_status_text($status) {
	switch($status) {
		case 0:
			return t('Normal');
		case 1:
			return t('Under approved');
		default:
			return t('Unknown');
	}
}

/**
 * Implementation of hook_help().
 */
function cert_issue_help($path, $arg) {
	switch ($path) {
		case 'user/certs':
			$output = t('List my certificates, clamed and issued.');
			break;
		case 'user/claim':
			$output = t('Claim system preloaded certificates.');
			break;
		case 'user/exchange':
			$output = t('Apply for certificates exchange.');
			break;
		case 'certificate/massiveupload': 
			$output = t('If you want to massive upload the certificates which are already issued, please use this feature.');
			break;
		case 'certificate/exchangerolls': 
			$output = t('Add roll for certificates exchange, or manipulate the status of rolls.');
			break;
	}
	if (isset($output))
		return $output;
}

/**
 * Implementation of hook_permission().
 */
function cert_issue_permission() {
	return array(
		'preload certificates' => array(
			'title' => t('Upload Massive certificates already issued'),
		),
		'claim certificates' => array(
			'title' => t('Claim already issued certificates'),
		),
		'admin certificates exchange rolls' => array(
			'title' => t('Administrate certificates exchange rolls'),
		),
	);
}

/**
 * Implementation of hook_theme().
 */
function cert_issue_theme() {
	return array(
		'cert_issue_exchange_rolls_form' => array(
			'render element' => 'form', 
		),
	);
}

/**
 * Implementation of hook_menu().
 */
function cert_issue_menu() {
	$items=array();
	$items['certificate/massiveupload'] = array(
		'title' => 'Upload Massive certificates already issued',
		'weight' => 3,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_massiveupload_form'),
		'access callback' => 'user_access',
		'access arguments'=> array('preload certificates'),
	);
	$items['certificate/massiveupload/form'] = array(
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'title' => 'Upload Massive certificates already issued',
		'weight' => 1,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_massiveupload_form'),
		'access callback' => 'user_access',
		'access arguments'=> array('preload certificates'),
	);
	$items['certificate/massiveupload/query'] = array(
		'type' => MENU_LOCAL_TASK,
		'title' => 'Query uploaded certs',
		'weight' => 2,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_massiveupload_query_form'),
		'access callback' => 'user_access',
		'access arguments'=> array('preload certificates'),
	);

	$items['certificate/massiveupload/revoke/%certissue/%student'] = array(
		'type' => MENU_CALLBACK,
		'title' => 'Revoke certificate',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_revoke_cert_form', 3, 4),
		'access callback' => 'cert_issue_revoke_cert_form_access',
		'access arguments'=> array(3, 4),
	);
	$items['certificate/exchangerolls'] = array(
		'title' => 'Certificates Exchange Roll Management',
		'weight' => 4,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_exchange_rolls_form'),
		'access callback' => 'user_access',
		'access arguments'=> array('admin certificates exchange rolls'),
	);
	$items['certificate/exchangerolls/%rollsview'] = array(
		'type' => MENU_VISIBLE_IN_BREADCRUMB,
		'title callback' => 'cert_issue_exchange_rolls_view_form_title', 
		'title arguments' => array(2),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_exchange_rolls_view_form', 2),
		'access callback' => 'user_access',
		'access arguments'=> array('admin certificates exchange rolls'),
	);
	$items['certificate/exchangerolls/%rollsview/reject/%certissue'] = array(
		'type' => MENU_CALLBACK,
		'title' => 'Reject Certificate Exchange Request', 
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_exchange_rolls_reject_form', 2, 4),
		'access callback' => 'cert_issue_exchange_rolls_reject_form_access',
		'access arguments' => array(2, 4),
	);
	$items['user/certs'] = array(
		'title' => 'My certificates',
		'menu_name' => 'user-menu',
		'plid' => '0',
		'weight' => 0,
		'page callback' => 'cert_issue_user_certs_page',
		'access callback' => 'cert_issue_user_certs_page_access',
	);
	$items['user/claim'] = array(
		'title' => 'Claim already issued certificates',
		'menu_name' => 'user-menu',
		'plid' => '0',
		'weight' => 1,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_user_claim_form'),
		'access callback' => 'cert_issue_user_claim_access',
	);
	$items['user/exchange'] = array(
		'title' => 'Exchange certificates',
		'menu_name' => 'user-menu',
		'plid' => '0',
		'weight' => 2,
		'page callback' => 'cert_issue_user_exchange_page',
		'access callback' => 'cert_issue_user_certs_page_access',
	);
	$items['user/exchange/%cer'] = array(
		'type' => MENU_CALLBACK,
		'title callback' => 'cert_issue_user_exchange_form_title', 
		'title arguments' => array(2),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cert_issue_user_exchange_form', 2),
		'access callback' => 'cert_issue_user_exchange_form_access',
		'access arguments'=> array(2),
	);
	return $items;
}

function _cert_issue_is_file_spreadsheet($file) {
	if(!preg_match('/\.xlsx{0,1}$/i', $file->filename)) return array();
	include_once(DRUPAL_ROOT.'/sites/all/libraries/phpexcel/PHPExcel.php');
	$result=0;
	switch($format=PHPExcel_IOFactory::identify($file->uri)) {
		case 'Excel5':
		case 'Excel2007':
		try {
			$objReader = PHPExcel_IOFactory::createReader($format);
			$objReader->setReadDataOnly(true);
			$objPHPExcel = $objReader->load($file->uri);
			$result=$objPHPExcel->getSheetCount()>0;
			$objPHPExcel->disconnectWorksheets();
			unset($objPHPExcel);
			unset($objReader);
		} catch(Exception $exp) {
			return array($exp->getMessage());
		}
	}
	if($result) return array();
	else return array(t('It is not a valid spreadsheet file.'));
}

function cert_issue_massiveupload_form($form, $form_state) {
	if(!isset($form_state['storage']['step'])) {
		unset($form_state['storage']);
		$form_state['storage']['step']=1;
	}

	if($form_state['storage']['step']==1)
		$form=cert_issue_massiveupload_form_step1($form, $form_state);
	else if($form_state['storage']['step']==2)
		$form=cert_issue_massiveupload_form_step2($form, $form_state);
	return $form;
}

function cert_issue_massiveupload_form_step1($form, $form_state) {
	$options=array();
	for($i=1980;$i<=(int)date('Y');$i++) {
		$options+=array($i.'02'=>t('!year winter',array('!year'=>$i)));
		$options+=array($i.'08'=>t('!year summer',array('!year'=>$i)));
	}
	$form['organization']=array(
		'#type' => 'select',
		'#title' => t('Organization'),
		'#required' => TRUE,
		'#options' => $options,
		'#default_value' => isset($form_state['storage']['oid'])?$form_state['storage']['oid']:NULL,
	);
	$rdbo=db_query('SELECT * FROM {certificates} ORDER BY cid');
	$options=array();
	foreach($rdbo as $r) {
		$options+=array(
			$r->cid=>sprintf('%s %s', $r->series, $r->name),
		);
	}
	$form['certificatetype']=array(
		'#type' => 'select',
		'#title' => t('Certificate Type'),
		'#required' => TRUE,
		'#options' => $options,
		'#default_value' => isset($form_state['storage']['cid'])?$form_state['storage']['cid']:NULL,
	);
	$form['autocreate']=array(
		'#type' => 'checkbox',
		'#title' => t('Auto create in-exist certificate operations.'),
		'#default_value' => TRUE,
	);
	$form['massivefile']=array(
		'#type' => 'managed_file',
		'#title' => t('Data file'),
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['fid'])?$form_state['storage']['fid']:0,
		'#description' => t('Only .xls and .xlsx spreadsheets are supported.'),
		'#upload_validators' => array('file_validate_extensions' => array('xls xlsx'), '_cert_issue_is_file_spreadsheet'=>array()),
	);
	$form['save']=array(
		'#type' => 'submit',
		'#value' => t('Next Step >'),
	);
	$form['#validate'][]='cert_issue_massiveupload_form_step1_validate';
	$form['#submit'][]='cert_issue_massiveupload_form_step1_submit';
	return $form;
}

function cert_issue_massiveupload_form_step1_validate($form, $form_state) {
	if(!$form_state['values']['autocreate'] &&
		!certificate_operations_load($form_state['values']['certificatetype'], $form_state['values']['organization'])) {
			form_set_error('organization',t('The selected organization does not contain selected certificate.'));
			form_set_error('certificatetype');
	}
}

function cert_issue_massiveupload_form_step1_submit($form, &$form_state) {
	if($form_state['values']['autocreate']) {
		// First merge th organizations table
		$year=substr($form_state['values']['organization'],0,4);
		$name=substr($form_state['values']['organization'],4,2)=='02'?t('!year winter',array('!year'=>$year)):t('!year summer',array('!year'=>$year));
		db_merge('operations')->key(array('oid'=>$form_state['values']['organization']))->fields(array(
			'year' => $year,
			'name' => $name,
		))->execute();
		// Then merge th c_i table
		if(!certificate_operations_load($form_state['values']['certificatetype'], $form_state['values']['organization'])) {
			db_insert('certificates_operations')->fields(array(
				'oid' => $form_state['values']['organization'],
				'cid' => $form_state['values']['certificatetype'],
				'visible' => 1,
				'status' => 0,
			))->execute();
		}
	}
	$form_state['storage']['oid']=$form_state['values']['organization'];
	$form_state['storage']['cid']=$form_state['values']['certificatetype'];
	$form_state['storage']['coid']=db_query(
		'SELECT coid FROM {certificates_operations} '.
		'WHERE cid=:cid AND oid=:oid',
		array(':cid'=>$form_state['values']['certificatetype'], ':oid'=> $form_state['values']['organization'])
	)->fetchField();
	$form_state['storage']['fid']=$form_state['values']['massivefile'];
	$form_state['rebuild']=TRUE;
	$form_state['storage']['step']=2;
}

function cert_issue_massiveupload_form_step2($form, $form_state) {
	$form['#attached']['css']=array(
		'.inline-element-div label, .inline-element-div select, .inline-element-div input, .inline-element-div div.form-item { display: inline;}'.
		'body.sidebar-first div #post-content { width: 960px; }'.
		'div#sidebar { display: none; }' => array('type'=>'inline')
	);
	include_once(DRUPAL_ROOT.'/sites/all/libraries/phpexcel/PHPExcel.php');
	$file=file_load($form_state['storage']['fid']);
	$uri = drupal_realpath($file->uri);
	if(interface_exists('SaeInterface')) {
		file_put_contents( SAE_TMP_PATH . $file->filename, file_get_contents($uri));
		$uri=SAE_TMP_PATH . $file->filename;
	}
	$format=PHPExcel_IOFactory::identify($uri);
	$objReader = PHPExcel_IOFactory::createReader($format);
	$objReader->setReadDataOnly(true);
	$objPHPExcel = $objReader->load($uri);
	$max_cols=$objPHPExcel->getActiveSheet()->getHighestColumn();
	$max_rows=$objPHPExcel->getActiveSheet()->getHighestRow();

	$co=certificate_operations_load($form_state['storage']['cid'], $form_state['storage']['oid']);
	$form['description']=array(
		'#type' => 'item',
		'#requires' => TRUE,
		'#title' => t('Selected organization'),
		'#markup' => t('!org !series !cname',
			array('!org'=>$co->oname, '!series'=>$co->series, '!cname'=>$co->cname)),
	);

	$options=drupal_map_assoc(range(1,$max_rows));
	$form['issuedate']=array(
		'#type' => 'date',
		'#title' => t('Certificate issue date'),
		'#default_value' => array(
			'year' => substr($form_state['storage']['oid'],0,4),
			'month' => (int)substr($form_state['storage']['oid'],4,2),
			'day' => 1,
		),
		'#required' => TRUE,
	);

	$form['prefix']=array(
		'#markup' => '<div class="inline-element-div">',
	);
	$i=1;
	$form['beginrow']=array(
		'#type' => 'select',
		'#title' => t('Data started at row'),
		'#description' => t('Please select where the data series begins, not the row where header locates.'),
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['beginrow_col'])?$form_state['storage']['beginrow_col']:'2',
	);
	$options=drupal_map_assoc(range('A',$max_cols));
	foreach($options as $key=>$val) {
		if(!$objPHPExcel->getActiveSheet()->getColumnDimension($key)->getVisible())
			unset($options[$key]);
	}
	$options_with_none=array('0'=>t('None'))+$options;
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['ticket_number']=array(
		'#type' => 'select',
		'#title' => t('Ticket number at col'),
		'#options' => $options_with_none,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['ticket_number_col'])?$form_state['storage']['ticket_number_col']:'0',
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['certid']=array(
		'#prefix' =>'<div style="width: 400px; display: inline; left: 400px;">',
		'#suffix' =>'</div>',
		'#type' => 'select',
		'#title' => t('Certificate number at col'),
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['certid_col'])?$form_state['storage']['certid_col']:NULL,
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['name']=array(
		'#type' => 'select',
		'#title' => t('Real name at col'),
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['name_col'])?$form_state['storage']['name_col']:NULL,
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['pyname']=array(
		'#type' => 'select',
		'#title' => t('Pinyin name at col'),
		'#options' => $options_with_none,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['pyname_col'])?$form_state['storage']['pyname_col']:'0',
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['gender']=array(
		'#type' => 'select',
		'#title' => t('Gender at col'),
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['gender_col'])?$form_state['storage']['gender_col']:NULL,
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['birthdate']=array(
		'#type' => 'select',
		'#title' => t('Birth date at col'),
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['birthdate_col'])?$form_state['storage']['birthdate_col']:NULL,
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['idcard_type']=array(
		'#type' => 'select',
		'#title' => t('ID Card type at col'),
		'#options' => $options_with_none,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['idcard_type_col'])?$form_state['storage']['idcard_type_col']:'0',
	);
	$form['middilefix'.$i++]=array(
		'#markup' => '</div><div class="inline-element-div">',
	);
	$form['idcardnumber']=array(
		'#type' => 'select',
		'#title' => t('ID Card nubmer at col'),
		'#options' => $options_with_none,
		'#required' => TRUE,
		'#default_value' => isset($form_state['storage']['idcardnumber_col'])?$form_state['storage']['idcardnumber_col']:'0',
	);
	$form['suffix']=array(
		'#markup' => '</div>',
	);

	// Display raw data for the spreadsheet
	$origrows=$objPHPExcel->getActiveSheet()->rangeToArray(
		'A1:'.($max_cols>'L'?'L':$max_cols).($max_rows>10?'10':$max_rows),	// The worksheet range that we want to retrieve
		'',			// Value that should be returned for empty cells
		TRUE,		// Should formulas be calculated (the equivalent of getCalculatedValue() for each cell)
		TRUE,		// Should values be formatted (the equivalent of getFormattedValue() for each cell)
		FALSE		// Should the array be indexed by cell row and cell column
	);
	$rows=array();
	$i=1;
	foreach($origrows as $row) {
		array_unshift($row, array('data'=>$i++, 'header'=>TRUE));
		$rows[]=$row;
	}
	$header=range('A',($max_cols>'L'?'L':$max_cols));
	array_unshift($header, sprintf('[%s]',$objPHPExcel->getActiveSheet()->getTitle()));
	$objPHPExcel->disconnectWorksheets();
	unset($objPHPExcel);
	unset($objReader);
	$form['demotitle']=array(
		'#type' => 'item',
		'#title' => t('Raw data for @filename', array('@filename'=>$file->filename)),
		'#markup' => t('Note: the raw data shows the hidden rows and columns, which means these rows and column will be proceeded.'),
	);
	$form['demo']=array(
		'#markup' => theme('table',array('header'=>$header, 'rows'=>$rows)),
	);

	$form['previous']=array(
		'#type' => 'submit',
		'#value' => t('< Previous Step'),
		'#submit' => array('cert_issue_massiveupload_form_step2_submit_previous'),
		'#limit_validation_errors' => array(),
	);
	$form['submit']=array(
		'#type' => 'submit',
		'#value' => t('Upload data file & save'),
	);

	$form['#validate'][]='cert_issue_massiveupload_form_step2_validate';
	$form['#submit'][]='cert_issue_massiveupload_form_step2_submit';
	return $form;
}

function cert_issue_massiveupload_form_step2_validate($form, $form_state) {
	include_once(DRUPAL_ROOT.'/sites/all/libraries/phpexcel/PHPExcel.php');
	if($form_state['values']['certid'] && $form_state['values']['name'] && $form_state['values']['gender']
		&& $form_state['values']['birthdate'])
	{
		$file=file_load($form_state['storage']['fid']);
		$uri=drupal_realpath($file->uri);
		if(defined('SAE_TMP_PATH')) {
			file_put_contents( SAE_TMP_PATH . $file->filename, file_get_contents($uri));
			$uri=SAE_TMP_PATH . $file->filename;
		}
		$format=PHPExcel_IOFactory::identify($uri);
		$objReader = PHPExcel_IOFactory::createReader($format);
		$objReader->setReadDataOnly(true);
		$objPHPExcel = $objReader->load($uri);
		$objWorksheet = $objPHPExcel->getActiveSheet();
		$row=$form_state['values']['beginrow'];
		$max_rows=$objWorksheet->getHighestRow();
		do {
			$row=(string)$row;
	
			// Test certid
			$certid=trim($objWorksheet->getCell($form_state['values']['certid'].$row)->getCalculatedValue());

			if(empty($certid)) {
				form_set_error('certid', t('!cord: The certid is empty.',
					array('!cord'=>$form_state['values']['certid'].$row)));
				break;
			} 

			// Test name
			$name=trim($objWorksheet->getCell($form_state['values']['name'].$row)->getCalculatedValue());
			if(empty($name)) {
				form_set_error('name', t('!cord: The name is empty.',
					array('!cord'=>$form_state['values']['name'].$row)));
				break;
			}

			// Test pyname
			if($form_state['values']['pyname']) {
				$pyname=strtoupper(trim($objWorksheet->getCell($form_state['values']['pyname'].$row)->getCalculatedValue()));
				if(!empty($pyname) && !preg_match('/^[A-Z ]+$/', $pyname)) {
					form_set_error('pyname', t('!cord: The alphabet name !val is not valid.',
						array('!cord'=>$form_state['values']['pyname'].$row, '!val' => $pyname)
					));
					break;
				}
			}

			// Test gender
			$gender=trim($objWorksheet->getCell($form_state['values']['gender'].$row)->getCalculatedValue());
			if(!in_array($gender, array('1','2',t('Male'),t('Female')))) {
				form_set_error('gender', t('!cord: The gender !val is invalid.',
					array('!cord'=>$form_state['values']['gender'].$row, '!val' => $gender)
				));
				break;
			}

			// Test birthdate
			if($form_state['values']['birthdate']) {
				$birthdate=trim($objWorksheet->getCell($form_state['values']['birthdate'].$row)->getCalculatedValue());
				$birthdate=preg_replace('/-/','',$birthdate);
				if(!empty($birthdate) && !preg_match('/^[0-9]+$/', $birthdate)) {
					form_set_error('birthdate', t('!cord: The birthdate !val is invalid.',
						array('!cord'=>$form_state['values']['birthdate'].$row, '!val' => $birthdate)
					));
					break;
				}
				if(strlen($birthdate)==6) {
					if(!_student_is_date_validate($birthdate.'01')) {
						form_set_error('birthdate', t('!cord: The birthdate !val is invalid.',
							array('!cord'=>$form_state['values']['birthdate'].$row, '!val' => $birthdate)
						));
						break;
					}
				} else if(strlen($birthdate)==8) {
					if(!_student_is_date_validate($birthdate)) {
						form_set_error('birthdate', t('!cord: The birthdate !val is invalid.',
							array('!cord'=>$form_state['values']['birthdate'].$row, '!val' => $birthdate)
						));
						break;
					}
				} else {
					form_set_error('birthdate', t('!cord: The birthdate !val is invalid.',
						array('!cord'=>$form_state['values']['birthdate'].$row, '!val' => $birthdate)
					));
				}
			}

			// Test idcard_type
			if($form_state['values']['idcard_type']) {
				$idcard_type=trim($objWorksheet->getCell($form_state['values']['idcard_type'].$row)->getCalculatedValue());
				if(!empty($idcard_type) && !preg_match('/^[0-9]$/', $idcard_type)) {
					form_set_error('idcard_type', t('!cord: The idcard type !val is invalid.',
						array('!cord'=>$form_state['values']['idcard_type'].$row, '!val' => $birthdate)
					));
					break;
				}
			}

			// Test idcard number
			if($form_state['values']['idcardnumber']) {
				$idcardnumber=strtoupper(trim($objWorksheet->getCell($form_state['values']['idcardnumber'].$row)->getCalculatedValue()));
				if(!empty($idcard_type) && $idcard_type==0 && _student_is_idcardn_validate($idcardnumber)) {
					form_set_error('idcard_type', t('!cord: The idcard number !val is invalid.',
						array('!cord'=>$form_state['values']['idcardnumber'].$row, '!val' => $birthdate)
					));
					break;
				}
				$student=db_query('SELECT * FROM {students} WHERE idcard_type=:idcard_type AND idcard_number=:idcard_number',
					array(':idcard_type'=>$idcard_type,':idcard_number'=>$idcardnumber))->fetchObject();
				if(!$student) break;
				if(($student->name != $name && $student->exname != $name) || ($student_gender != $gender)) {
					$form_set_error('idcardnumber',
						t('!cord: The idcard number !val does not match what the users have input (!name, !gender).',
							array('!cord'=>$form_state['values']['idcardnumber'].$row, '!val' => $idcardnumber,
								'!name'=>empty($student->exname)?$student->name:(sprintf('%s (%s)', $student->name, $student->exname))
							)
						)
					);
					break;
				}
			}
			
		} while ($row++<$max_rows);

		$objWorksheet->disconnectCells();
		$objPHPExcel->disconnectWorksheets();
		unset($objPHPExcel);
		unset($objReader);
	}
}

function cert_issue_massiveupload_form_step2_submit($form, &$form_state) {
	$file=file_load($form_state['storage']['fid']);
	$wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
	$uri = $wrapper->getDirectoryPath() . "/" . file_uri_target($file->uri);
	$format=PHPExcel_IOFactory::identify($uri);
	$objReader = PHPExcel_IOFactory::createReader($format);
	$objReader->setReadDataOnly(true);
	$objPHPExcel = $objReader->load($uri);
	$objWorksheet = $objPHPExcel->getActiveSheet();
	$i=0;
	$max_rows=$objWorksheet->getHighestRow();
	for($row=$form_state['values']['beginrow'];$row<=$max_rows;$row++) {
		$certid=trim($objWorksheet->getCell($form_state['values']['certid'].$row)->getCalculatedValue());
		if($form_state['values']['ticket_number'])
			$ticket_number=trim($objWorksheet->getCell($form_state['values']['ticket_number'].$row)->getCalculatedValue());
		else
			$ticket_number='';
		$name=trim($objWorksheet->getCell($form_state['values']['name'].$row)->getCalculatedValue());
		if($form_state['values']['pyname'])
			$pyname=trim($objWorksheet->getCell($form_state['values']['pyname'].$row)->getCalculatedValue());
		else
			$pyname='';
		if($form_state['values']['idcard_type'])
			$idcard_type=trim($objWorksheet->getCell($form_state['values']['idcard_type'].$row)->getCalculatedValue());
		else
			$idcard_type=NULL;
		if($form_state['values']['idcardnumber'])
			$idcardnumber=strtoupper(trim($objWorksheet->getCell($form_state['values']['idcardnumber'].$row)->getCalculatedValue()));
		else
			$idcardnumber='';
		$birthdate=trim($objWorksheet->getCell($form_state['values']['birthdate'].$row)->getCalculatedValue());
		$birthdate=preg_replace('/-/','',$birthdate);
		$gender=trim($objWorksheet->getCell($form_state['values']['gender'].$row)->getCalculatedValue());
		if(in_array($gender,array('1',t('Male'))))
			$gender=1;
		else
			$gender=2;
		$claimedby=(int)db_query('SELECT uid FROM {students} WHERE idcard_number=:idcard_number',
			array(':idcard_number'=>$idcardnumber))->fetchField();
		$r=db_insert('certificates_issues')->fields(array(
			'coid' => $form_state['storage']['coid'],
			'certid' => $certid,
			'ticket_number' => $ticket_number,
			'name' => $name,
			'foreign_name' => $pyname,
			'idcard_type' => $idcard_type,
			'idcard_number' => $idcardnumber,
			'date_of_birth' => $birthdate,
			'gender' => $gender,
			'issuedate' => sprintf("%04d%02d%02d",$form_state['values']['issuedate']['year'], $form_state['values']['issuedate']['month'], $form_state['values']['issuedate']['day']),
			'claimedby' => $claimedby,
		))->execute();
		if($r) {
			$i++;
			$form_state['storage']['beginrow_col']=$form_state['values']['beginrow'];
			$form_state['storage']['ticket_number_col']=$form_state['values']['ticket_number'];
			$form_state['storage']['certid_col']=$form_state['values']['certid'];
			$form_state['storage']['name_col']=$form_state['values']['name'];
			$form_state['storage']['pyname_col']=$form_state['values']['pyname'];
			$form_state['storage']['gender_col']=$form_state['values']['gender'];
			$form_state['storage']['birthdate_col']=$form_state['values']['birthdate'];
			$form_state['storage']['idcard_type_col']=$form_state['values']['idcard_type'];
			$form_state['storage']['idcardnumber_col']=$form_state['values']['idcardnumber'];
		}
	}

	$objWorksheet->disconnectCells();
	$objPHPExcel->disconnectWorksheets();
	unset($objPHPExcel);
	unset($objReader);
	$form_state['rebuild']=TRUE;
	unset($form_state['storage']['fid']);
	$form_state['storage']['step']=1;
	drupal_set_message(t('!num records are imported.', array('!num'=>$i)));
	watchdog('certificate',
		'!num records are imported..', array(
			'!num'=>$i,
			),
		WATCHDOG_INFO
	);
}

function cert_issue_massiveupload_form_step2_submit_previous($form, &$form_state) {
	$form_state['rebuild']=TRUE;
	$form_state['storage']['step']=1;
}

function cert_issue_user_certs_page_access() {
	$user=$GLOBALS['user'];
	if(student_load($user)) {
		return db_query('SELECT EXISTS( SELECT * FROM {certificates_issues} WHERE claimedby=:uid)',
			array(':uid'=>$user->uid))->fetchField();
	} else return FALSE;
}

function cert_issue_user_certs_page() {
	$user=$GLOBALS['user'];
	$query=db_select('certificates_issues','ci')
		->condition('ci.claimedby',$user->uid)
		->fields('ci',array('certid','issuedate','status'));
	$query->innerJoin('certificates_operations','co','co.coid=ci.coid');
	$query->innerJoin('operations','o','co.oid=o.oid');
	$query->innerJoin('certificates','c','co.cid=c.cid');
	$query->addExpression('o.name','oname');
	$query->addExpression('c.name','cname');
	$query->fields('c',array('series'));
	$header=array(
		array('data'=>t('Organizations series'),'field'=>'o.oid'),
		array('data'=>t('Series'), 'field'=>'c.series'),
		array('data'=>t('Specification name')),
		array('data'=>t('Certificate no'), 'field'=>'ci.certid'),
		array('data'=>t('Status'), 'field'=>'ci.status'),
	);
	$rows=array();
	$query->extend('TableSort')->orderByHeader($header)->extend('PagerDefault')->limit(20);
	$output = '';
	$rdbo=$query->execute();
	foreach($rdbo as $r) {
		$rows[]=array(
			$r->oname,
			$r->series,
			$r->cname,
			$r->certid,
			_cert_issue_get_status_text($r->status),
		);
	}
	$output .= theme('table', array('header'=>$header, 'rows'=>$rows));
	$output .= theme('pager');

	if(cert_issue_user_claim_access())
		$output .= '<div>'.l(t('Want to claim more certificates?'), 'user/claim').'</div>';
	return $output;
}

function cert_issue_user_claim_access($user=NULL) {
	if(empty($user)) $user=$GLOBALS['user'];
	if(isset($user->uid) && $user->uid && user_access('claim certificates')) {
		$student=student_load($user);
		if(!$student) return FALSE;
		else return !user_access('preload certificates', $user);
	} else return FALSE;
}

function cert_issue_user_claim_form($form, $form_state) {
	$student=student_load($GLOBALS['user']);
	$form['description']=array(
		'#markup' => t('Please select the certificate you wan to claim. ').
			t('If your certificates is not listed here, please contact us.').'<br/>'.
			t('Tip: if you have changed your name in the pass, please put it down at !url, so that we could make it recognized.',
				array('!url'=>l(t('here'), 'user/'.$student->uid.'/edit'))),
	);
	$header=array(
		t('Organizations series'),
		t('Specification name'),
		t('Certificate no'),
		t('True name'),
		t('Birth date'),
	);
	$query=db_select('certificates_issues','ci')
		->condition('ci.claimedby',0)
		->condition('ci.gender',$student->gender)
		->fields('ci',array('ciid','certid','name','date_of_birth'));
	if($student->exname) {
		$condition=db_or()->condition('ci.name',$student->name)->condition('ci.name',$student->exname);
		$query->condition($condition);
		unset($condition);
	} else
		$query->condition('ci.name',$student->name);
	$query->condition('ci.date_of_birth',substr($student->date_of_birth,0,6));
	$query->innerJoin('certificates_operations','co','co.coid=ci.coid');
	$query->innerJoin('operations','o','co.oid=o.oid');
	$query->innerJoin('certificates','c','co.cid=c.cid');
	$query->addExpression('o.name','oname');
	$query->addExpression('c.name','cname');
	$query->fields('c',array('series'));
	$query->orderBy('o.year')->orderBy('o.oid')->orderBy('c.cid');

	$rows=array();
	$rdbo=$query->execute();
	foreach($rdbo as $r) {
		$rows[$r->ciid]=array(
			$r->oname,
			$r->cname,
			$r->certid,
			$r->name,
			$r->date_of_birth,
		);
	}
	$form['certs']=array(
		'#type' => 'tableselect',
		'#header' => $header,
		'#options' => $rows,
		'#required' => empty($rows),
		'#empty' => t('No available certificates for you to claim.'),
	);
	if(!empty($rows))
		$form['claim']=array(
			'#type' => 'submit',
			'#value' => t('Claim selected certificates & Proceed'),
		);
	return $form;
}

function cert_issue_user_claim_form_submit($form, &$form_state) {
	$certs=array_keys(array_filter($form_state['values']['certs']));
	$i=0;
	foreach($certs as $cert) {
		$i+=db_update('certificates_issues')->condition('claimedby',0)->condition('ciid',$cert)->fields(array(
			'claimedby' => $GLOBALS['user']->uid,
		))->execute();
	}
	if($i) {
		drupal_set_message(t('You claimed !num certificates.', array('!num'=>$i)));
		$certobj=certissue_load($certs);
		watchdog('certificate',
			'Claimed certificate !cname !certid.', array(
				'!cname'=>$certobj->cname,
				'!certid'=>$certobj->certid,
				),
			WATCHDOG_INFO
		);
	}
	if(!cert_issue_user_claim_access())
		$form_state['redirect']='user/certs';
}

function cert_issue_exchange_rolls_form($form, &$form_state) {
	$form['#attached']['css']=array(
		'.inline-element-div label, .inline-element-div select, .inline-element-div input, .inline-element-div div.form-item { display: inline; }' => array('type'=>'inline')
	);

	$form['addrolls']=array(
		'#type' => 'fieldset',
		'#title' => t('Add new roll for certificates exchange'),
		'#collapsible' => TRUE,
	);
	$rdbo=db_query('SELECT c.* FROM {certificates} c WHERE NOT EXISTS(SELECT cer.* FROM {certificates_exchange_rolls} cer '.
		'INNER JOIN {certificates_operations} co ON cer.coid=co.coid '.
		'WHERE co.cid=c.cid AND (cer.status=2 OR cer.status=0) '.
		')');
	$options=array();
	foreach($rdbo as $r) {
		$options+=array(
			(string)$r->cid=>sprintf("%s - %s",$r->series, $r->name)
		);
	}
	$form['addrolls']['cid_prefix']=array(
		'#type' => 'item',
		'#title' => t('Student may apply'),
		'#required' => TRUE,
	);
	$form['addrolls']['cid']=array(
		'#type' => 'select',
		'#options' => $options,
		'#title' => t('New certificate'),
		'#title_display' => 'invisible',
		'#required' => TRUE,
		'#default_value' => NULL,
	);
	$form['addrolls']['cid_orig_prefix']=array(
		'#type' => 'item',
		'#title' => t(', if he has a valid'),
		'#required' => TRUE,
	);
	$rdbo=db_query('SELECT * FROM {certificates} ORDER BY series, cid');
	$options=array();
	foreach($rdbo as $r) {
		$options+=array(
			(string)$r->cid=>sprintf("%s - %s",$r->series, $r->name)
		);
	}
	$form['addrolls']['cid_orig']=array(
		'#type' => 'select',
		'#title' => t('Old certificate'),
		'#title_display' => 'invisible',
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => NULL,
	);
	$options=array('0'=>t('nothing else'))+$options;
	$form['addrolls']['ccid_orig_extra_prefix']=array(
		'#type' => 'item',
		'#title' => t('and'),
		'#required' => TRUE,
	);
	$form['addrolls']['cid_orig_extra']=array(
		'#type' => 'select',
		'#title' => t('Old certificate'),
		'#title_display' => 'invisible',
		'#options' => $options,
		'#required' => TRUE,
		'#default_value' => '-1',
	);
	$form['addrolls']['enabled']=array(
		'#type' => 'checkbox',
		'#title' => t('Make it enabled for students to apply right now'),
		'#default_value' => TRUE,
		'#description' => t('You can only close (end) a roll, after enabling it.'),
	);
	$form['addrolls']['save']=array(
		'#type' => 'submit',
		'#value' => t('Add roll'),
		'#weight' => 100,
	);
	$form['#attached']['css'][]=array(
		'data'=>'div.form-item-enabled div.description {color: red; font-weight: bold;}',
		'type'=>'inline'
	);

	$header=array(
		array('data' => t('Series'), 'field'=> 'series'),
		array('data' => t('Specification'), 'field'=> 'name'),
		array('data' => t('Exchange requirements')),
		array('data' => t('Status'), 'field'=> 'status', 'sort'=>'desc'),
		array('data' => t('Operation')),
	);
	$query=db_select('certificates_exchange_rolls','cer')->fields('cer')
		->extend('TableSort')->orderByHeader($header)->extend('PagerDefault')->limit(20);
	$query->innerJoin('certificates_operations','co','cer.coid=co.coid');
	$query->innerJoin('certificates','c','c.cid=co.cid');
	$query->fields('c',array('series','name'));
	$form['rolls']=array(
		'#type' => 'fieldset',
	);
	$form['rolls']['title']=array(
		'#type' => 'item',
		'#title' => t('Existing rolls'),
	);
	$rdbo=$query->execute();
	$form['addrolls']['#collapsed']=$rdbo->rowCount();
	$form['rolls']['cerid']=array();
	foreach($rdbo as $r) {
		$form['rolls']['cerid'][$r->cerid]=array('#type'=>'hidden','#value'=>$r->cerid);
		$form['rolls']['series'][$r->cerid]=array('#markup'=>$r->series);
		$form['rolls']['name'][$r->cerid]=array('#markup'=>$r->name);
		$cid_orig=json_decode($r->cid_orig);
		$cids=array();
		foreach($cid_orig as $cid) {
			$cids[]=db_query('SELECT name FROM {certificates} WHERE cid=:cid',array(':cid'=>$cid))->fetchField();
		}
		if(count($cids)>1)
			$c='<ul><li>'.implode('</li><li>',$cids).'</li></ul>';
		else
			$c=$cids[0];
		$form['rolls']['cid_orig'][$r->cerid]=array('#markup'=>$c);
		switch($r->status) {
			case 0: // it is not enabled.
				$form['rolls']['status'][$r->cerid]=array('#markup'=>t('Openable'));
				$form['rolls']['submit'.$r->cerid]=array(
					'#type' => 'submit',
					'#value' => t('Open'),
					'#name' => 'open'.$r->cerid,
					'#limit_validation_errors'=>array(),
					'#submit' => array('cert_issue_exchange_rolls_form_open_submit'),
				);
				break;
			case 2: // it is not open.
				$form['rolls']['status'][$r->cerid]=array('#markup'=>l(t('Ongoing'), 'certificate/exchangerolls/'.$r->cerid, array('attributes'=>array('title'=>t('Click for details')))));
				$form['rolls']['submit'.$r->cerid]=array(
					'#type' => 'submit',
					'#name' => 'close'.$r->cerid,
					'#value' => t('Close'),
					'#limit_validation_errors'=>array(),
					'#submit' => array('cert_issue_exchange_rolls_form_close_submit'),
				);
				break;
			case 1: // it is closed
				$form['rolls']['status'][$r->cerid]=array('#markup'=>l(t('Closed'), 'certificate/exchangerolls/'.$r->cerid, array('attributes'=>array('title'=>t('Click for details')))));
				$form['rolls']['submit'.$r->cerid]=array('#markup'=>'');
		}
	}

	return $form;
}

function theme_cert_issue_exchange_rolls_form($variables) {
	$form=$variables['form'];
	$output ='';
	$output .= drupal_render($form['addrolls']);
	
	$header=array(
		array('data' => t('Series'), 'field'=> 'series'),
		array('data' => t('Specification'), 'field'=> 'name'),
		array('data' => t('Exchange requirements'), 'field'=> 'name'),
		array('data' => t('Status'), 'field'=> 'status', 'sort'=>'desc'),
		array('data' => t('Operation')),
	);
	$rows=array();
	foreach($form['rolls']['cerid'] as $cer) {
		if(!isset($cer['#type']) || $cer['#type']!='hidden') continue;
		$cerid=$cer['#value'];
		$rows[]=array(
			drupal_render($form['rolls']['series'][$cerid]),
			drupal_render($form['rolls']['name'][$cerid]),
			drupal_render($form['rolls']['cid_orig'][$cerid]),
			drupal_render($form['rolls']['status'][$cerid]),
			drupal_render($form['rolls']['submit'.$cerid]),
		);
	}
	if(!empty($rows)) {
		$output .= drupal_render($form['rolls']['title']);
		$output.=theme('table',array('header'=>$header,'rows'=>$rows,'empty'=>t('There is no defined rolls.')));
	} else unset($form['rolls']['title']);
	unset($form['rolls']);
	$output.=drupal_render_children($form);
	$output .= theme('pager');
	return $output;
}

function cert_issue_exchange_rolls_form_validate($form, $form_state) {
	if(empty($form_state['values']['cid']) || empty($form_state['values']['cid_orig'])) return;
	if($form_state['values']['cid']==$form_state['values']['cid_orig']) {
		form_set_error('cid');
		form_set_error('cid_orig', t('You cannot select the same value for both new and old certificate.'));
	}
	else if($form_state['values']['cid']==$form_state['values']['cid_orig_extra']) {
		form_set_error('cid');
		form_set_error('cid_orig_extra', t('You cannot select the same value for both new and old certificate.'));
	}
	else if($form_state['values']['cid_orig']==$form_state['values']['cid_orig_extra']) {
		form_set_error('cid_orig');
		form_set_error('cid_orig_extra', t('You cannot select the same value for both old certificates.'));
	}
}

function cert_issue_exchange_rolls_form_submit($form, $form_state) {
	$cid_orig=array((int)$form_state['values']['cid_orig']);
	if($form_state['values']['cid_orig_extra'])
		$cid_orig[]=(int)($form_state['values']['cid_orig_extra']);
	$oid=sprintf("%4d%02d",date('Y'),date('m')+20);
	db_merge('operations')->key(array('oid'=>$oid))->insertFields(array(
		'oid'=>$oid,
		'year'=>date('Y'),
		'name'=>t('!year !month cert exchange',array('!year'=>date('Y'), '!month'=>date('n'))),
	))->execute();
	db_merge('certificates_operations')->key(array('oid'=>$oid, 'cid'=>$form_state['values']['cid']))->insertFields(array(
		'oid'=>$oid,
		'cid'=>$form_state['values']['cid'],
		'visible'=>0,
		'status'=>0,
	))->execute();
	$coid=db_query('SELECT coid FROM {certificates_operations} WHERE cid=:cid AND oid=:oid',
		array(':cid'=>$form_state['values']['cid'], ':oid'=>$oid))->fetchField();
	$r=db_insert('certificates_exchange_rolls')->fields(array(
		'cid_orig' => json_encode($cid_orig),
		'coid' => $coid,
		'status' => $form_state['values']['enabled']?2:0,
	))->execute();
	if($r)
		if($form_state['values']['enabled']) {
			drupal_set_message(t('Roll added and published.'));
			$cname=db_query('SELECT name FROM {certificates} WHERE cid=:cid',array(':cid'=>$form_state['values']['cid']))->fetchField();
			watchdog('certificate',
				'Added and published new certificate exchange roll on !cname.', array(
					'!cname'=>$cname,
					),
				WATCHDOG_INFO
			);
		}
		else {
			drupal_set_message(t('Roll added.'));
			$cname=db_query('SELECT name FROM {certificates} WHERE cid=:cid',array(':cid'=>$form_state['values']['cid']))->fetchField();
			watchdog('certificate',
				'Added new certificate exchange roll on !cname.', array(
					'!cname'=>$cname,
					),
				WATCHDOG_INFO
			);
		}
}

function cert_issue_exchange_rolls_form_open_submit($form, $form_state) {
	$cerid=substr($form_state['triggering_element']['#name'],4);
	db_update('certificates_exchange_rolls')->fields(array(
		'status'=>2
	))->condition('cerid',$cerid)->execute();
	drupal_set_message(t('Roll opened.'));
	$cer=cer_load($cerid);
	watchdog('certificate',
		'Published certificate exchange roll !cname.', array(
			'!cname'=>$cer->cname,
			),
		WATCHDOG_INFO
	);
}

function cert_issue_exchange_rolls_form_close_submit($form, $form_state) {
	$cerid=substr($form_state['triggering_element']['#name'],5);
	db_update('certificates_exchange_rolls')->fields(array(
		'status'=>1
	))->condition('cerid',$cerid)->execute();
	drupal_set_message(t('Roll closed.'));
	$cer=cer_load($cerid);
	watchdog('certificate',
		'Closed certificate exchange roll !cname.', array(
			'!cname'=>$cer->cname,
			),
		WATCHDOG_INFO
	);
}

function cert_issue_user_exchange_page() {
	$output = '';
	$output .= t('In this page, you could deal with certificate exchange feature.');
	$output .= t('You will see current open rolls for you to select.');

	$header = array(
		t('New certificate to apply'),
		t('Requirements'),
		t('Operation'),
	);

	$rows=array();
	$rdbo=db_query('SELECT * FROM {certificates_exchange_rolls} WHERE status=2');
	foreach($rdbo as $r) { 
		$cer=cer_load($r->cerid);
		$rows[]=array(
			sprintf('%s %s', $cer->series, $cer->cname),
			$cer->cname_orig_formatted,
			cert_issue_user_exchange_form_access($cer)?l(t('Apply for this new certificate'),'user/exchange/'.$r->cerid):t('Cannot apply'),
		);
		$query=db_query('SELECT EXISTS (SELECT * FROM {certificates_issues} WHERE claimedby=:uid AND coid=:coid)',
			array(':uid'=>$GLOBALS['user']->uid, ':coid'=>$cer->coid));
		if($query->fetchField())
			$rows[count($rows)-1][count($rows[count($rows)-1])-1]=l(t('Already applied, check status'), 'user/certs');
	}
	$output.=theme('table',array('header'=>$header, 'rows'=>$rows, 'empty'=>t('There is no currently open rolls for certificate exchange.')));
	return $output;
}

function cer_load($cer) {
	$query=db_query('SELECT cer.*, c.cid, c.series, c.name AS cname FROM {certificates_exchange_rolls} cer '.
		'INNER JOIN {certificates_operations} co ON cer.coid=co.coid '.
		'INNER JOIN {certificates} c ON c.cid=co.cid '.
		'WHERE cer.cerid=:cerid',
		array(':cerid'=>$cer)
	); 
	$obj=$query->fetchObject();
	if(!$obj) return FALSE;
	$cid_orig=json_decode($obj->cid_orig);
	$obj->cid_orig=$cid_orig;
	$cids=array();
	foreach($cid_orig as $cid) {
		$cids[$cid]=db_query('SELECT name FROM {certificates} WHERE cid=:cid',array(':cid'=>$cid))->fetchField();
	}
	$obj->cname_orig=$cids;
	if(count($cids)>1)
		$c='<ul><li>'.implode('</li><li>',$cids).'</li></ul>';
	else
		$c=$cids[$cid];
	$obj->cname_orig_formatted=$c;
	return $obj;
}

function cert_issue_user_exchange_form_title($cer) {
	return t('Apply @cname to exchange',array('@cname'=>$cer->cname));
}

function cert_issue_user_exchange_form_access($cer) {
	if(isset($cer->status) && $cer->status <> 2) return FALSE;
	if(!cert_issue_user_certs_page_access()) return FALSE;
	$user=$GLOBALS['user'];

	$query=db_query('SELECT EXISTS( SELECT * FROM {certificates_issues} ci INNER JOIN {certificates_operations} co ON co.coid=ci.coid WHERE ci.claimedby=:uid AND co.cid=:cid)',
		array(':uid'=>$user->uid, ':cid'=>$cer->cid)
	);
	if($query->fetchField()) return FALSE;

	foreach($cer->cid_orig as $cid) {
		$query=db_query('SELECT EXISTS (SELECT * FROM {certificates_issues} ci INNER JOIN {certificates_operations} co ON co.coid=ci.coid WHERE ci.claimedby=:uid AND ci.status=0 AND co.cid=:cid)',
			array(':uid'=>$user->uid, ':cid'=>$cid));
		if($query->fetchField()==0) return FALSE;
	}
	return TRUE;
}

function cert_issue_user_exchange_form($form, &$form_state, $cer) {
	$user=$GLOBALS['user'];
	$form_state['storage']['charge']=array(
		'module'=>'cert_issue',
		'account'=>'certexchange',
		'ordertitle'=>drupal_get_title()
	);
	$certs=array();
	foreach($cer->cid_orig as $cid) {
		$query=db_query('SELECT ci.certid, c.series, c.name FROM {certificates_issues} ci '.
			'INNER JOIN {certificates_operations} co ON co.coid=ci.coid '.
			'INNER JOIN {certificates} c ON co.cid=c.cid '.
			'WHERE co.cid=:cid ORDER BY ci.issuedate DESC',
			array(':cid'=>$cid)
		);
		$r=$query->fetchObject();
		$certs[]=sprintf('%s %s', $r->series, $r->name).'<br/>'.t('No. @certid', array('@certid'=>$r->certid));
	}
	if(count($certs)>1)
		$certs_str='<ul><li>'.implode('</li><li>',$certs).'</li></ul>';
	else
		$certs_str=$certs[0];
	$form['cid_orig']=array(
		'#type' => 'item',
		'#title' => t('Your old certificates'),
		'#markup' => $certs_str,
	);

	$r=db_query('SELECT * FROM {certificates} WHERE cid=:cid',array(':cid'=>$cer->cid))->fetchObject();
	$form['cid']=array(
		'#type' => 'item',
		'#title' => t('Will be exchanged to certificates'),
		'#markup' => sprintf('%s %s', $r->series, $r->name),
	);
	$student=student_load($user);
	$form['picture']=array(
		'#type' => 'item',
		'#markup' => sprintf('<img src="%s" height="150" align="left" style="margin-right: 30px;"/>', $student->picture),
		'#states' => array(
			'visible' => array(
				':input[name="confirm"]' => array('checked' =>FALSE),
			),
		),
	);
	$form['name']=array(
		'#type' => 'item',
		'#title' => t('Your Name'),
		'#markup' => sprintf('%s<br/>%s', $student->name, $student->foreign_name),
		'#states' => array(
			'visible' => array(
				':input[name="confirm"]' => array('checked' =>FALSE),
			),
		),
	);
	$form['idcard']=array(
		'#type' => 'item',
		'#title' => t('Your IDCard number'),
		'#markup' => $student->idcard_number,
		'#states' => array(
			'visible' => array(
				':input[name="confirm"]' => array('checked' =>FALSE),
			),
		),
	);
	$form['birthdate']=array(
		'#type' => 'item',
		'#title' => t('Your birth date'),
		'#markup' => $student->date_of_birth,
		'#states' => array(
			'visible' => array(
				':input[name="confirm"]' => array('checked' =>FALSE),
			),
		),
	);
	$form['confirm']=array(
		'#type' => 'checkbox',
		'#title' => t('I have confirmed above information, there is no need to do furture modifications.'),
		'#description' => t('If you want to modify your personal information, please go !url.',
			array('!url'=>l(t('here'), 'user/'.$user->uid.'/edit'))),
		'#required' => TRUE,
	);
	$form['cancel']=array(
		'#type' => 'submit',
		'#value' => t('Cancel'),
		'#weight' => 100,
		'#submit' => array('cert_issue_user_exchange_form_cancel'),
		'#limit_validation_errors' => array(),
	);
	$form['submit']=array(
		'#type' => 'submit',
		'#weight' => 101,
		'#value' => t('Apply for certificate exchange'),
		'#states' => array(
			'visible' => array(
				':input[name="confirm"]' => array('checked' =>TRUE),
			),
		),
	);
	return $form;
}

function cert_issue_user_exchange_form_cancel($form, &$form_state) {
	$form_state['redirect'] = 'user/exchange';
}

function cert_issue_user_exchange_form_submit($form, &$form_state) {
	$student=student_load($GLOBALS['user']);
	$cer=$form_state['build_info']['args'][0];
	$r=db_insert('certificates_issues')->fields(array(
		'coid' => $cer->coid,
		'cerid' => $cer->cerid,
		'name' => $student->name,
		'foreign_name' => $student->foreign_name,
		'idcard_type' => $student->idcard_type,
		'idcard_number' => $student->idcard_number,
		'date_of_birth' => $student->date_of_birth,
		'gender' => $student->gender,
		'picture' => $student->photoid,
		'claimedby' => $student->uid,
		'status' => 1,
	))->execute();
	if($r) {
		$form_state['values']['ciid']=$r;
		drupal_set_message(t('Certificate exchange applied.'));
		watchdog('certificate',
			'Applied exchange on certificate !cname.', array(
				'!cname'=>$cer->cname,
				),
			WATCHDOG_INFO
		);
		$form_state['redirect'] = 'user/certs';
	}
}

function cert_issue_form_user_profile_form_alter(&$form, &$form_state) {
	$user=$form['#user'];
	if($user->uid) {
		$query=db_query('SELECT EXISTS( SELECT * FROM {certificates_issues} WHERE status=1 AND claimedby=:uid)',array(':uid'=>$user->uid));
		if($query->fetchField())
			$form_state['storage']['disable_edit']=TRUE;
	}
}

function cert_issue_user_view($user, $view_mode, $langcode) {
	if(!student_load($user)) return;
	// If we should redirect the url when there are certificate to claim
	if(cert_issue_user_claim_access($user) && $GLOBALS['user']->uid==$user->uid) {
		$student=student_load($user);
		$sql='SELECT count(*) '.
			'FROM {certificates_issues} ci INNER JOIN {certificates_operations} co ON co.coid=ci.coid '.
			'INNER JOIN {operations} o ON co.oid=o.oid '.
			'INNER JOIN {certificates} c ON co.cid=c.cid '.
			'WHERE ci.claimedby=0 AND ci.gender=:gender AND ci.date_of_birth=:dateofbirth '.
			'';
		if($student->exname) {
			$sql.='AND (ci.name=:name OR ci.name=:exname) ';
		} else
			$sql.='AND (ci.name=:name AND :exname=:exname)';
		$query=db_query($sql, array(
			':gender'=>$student->gender, ':name'=>$student->name,
			':exname'=>empty($student->exname)?'':$student->exname,
			':dateofbirth'=>substr($student->date_of_birth,0,6)
		));
		if($query->fetchField()) {
			if(strstr($_SERVER['HTTP_REFERER'], sprintf('%s%suser/%s/edit', $_SERVER['HTTP_HOST'], base_path(), $user->uid))) {
				drupal_goto('user/claim'); return;
			}
			else 
				drupal_set_message(l(t('There might be some certificates for you to claim.'), 'user/claim'), 'warning');
		}
	}

	// Now the certificate section
	$count=db_query('SELECT EXISTS(SELECT * FROM {certificates_issues} WHERE claimedby=:uid)', array(':uid'=>$user->uid))->fetchField();
	if($count) {
		$user->content['cert']=array(
			'#type' => 'user_profile_category',
			'#title' => t('Certificates'),
			'#weight' => '2',
		);
		$query=db_query('SELECT ci.ciid, ci.certid, ci.claimedby, c.name as cname, c.series FROM {certificates_issues} ci '.
			'INNER JOIN {certificates_operations} co ON co.coid=ci.coid '.
			'INNER JOIN {operations} o ON co.oid=o.oid '.
			'INNER JOIN {certificates} c ON co.cid=c.cid '.
			'WHERE claimedby=:uid AND ci.cerid IS NULL ORDER BY ci.certid',
			array(':uid'=>$user->uid)
		);
		$header=array(
			t('Series'),
			t('Specification'),
			t('Certificate Number')
		);
		if($GLOBALS['user']->uid!=$user->uid && user_access('preload certificates'))
			$header[]=t('Operation');
		$rows=array();
		$i=0;
		foreach($query as $r) {
			$rows[$i]=array(
				$r->series,
				$r->cname,
				$r->certid
			);
			if($GLOBALS['user']->uid!=$user->uid && user_access('preload certificates'))
				$rows[$i][]=l(t('Revoke'), sprintf('certificate/massiveupload/revoke/%s/%s', $r->ciid, $r->claimedby));
			if(++$i > 3) {
				$rows[$i]=array(
					array('data'=>l(t('More certificates...'), 'user/certs'), 'colspan'=>3)
				);
				break;
			}
		}
		$user->content['cert']['claimed']=array(
			'#type' => 'user_profile_item',
			'#title' => t('Claimed Certificates'),
			'#markup'=>theme('table',array('header'=>$header, 'rows'=>$rows))
		);
	}

	// Now the certificate exchange section
	$count=db_query('SELECT EXISTS(SELECT * FROM {certificates_issues} WHERE claimedby=:uid AND cerid IS NOT NULL)', array(':uid'=>$user->uid))->fetchField();
	if($count) {
		$header=array(
			t('Specification'),
			t('Status')
		);
		if($GLOBALS['user']->uid!=$user->uid && user_access('admin certificates exchange rolls'))
			$header[]=t('Operation');
		$query=db_query('SELECT ci.cerid, ci.ciid, c.name as cname, ci.status FROM {certificates_issues} ci '.
			'INNER JOIN {certificates_operations} co ON co.coid=ci.coid '.
			'INNER JOIN {operations} o ON co.oid=o.oid '.
			'INNER JOIN {certificates} c ON co.cid=c.cid '.
			'WHERE claimedby=:uid AND ci.cerid IS NOT NULL ORDER BY ci.status DESC, ci.cerid DESC, c.cid',
			array(':uid'=>$user->uid)
		);
		$rows=array();
		$i=0;
		foreach($query as $r) {
			$rows[$i++]=array(
				$r->cname,
				_cert_issue_get_status_text($r->status),
			);
			if($GLOBALS['user']->uid!=$user->uid && user_access('admin certificates exchange rolls'))
				if($r->status>0)
					$rows[$i-1][]=l(t('Reject'), sprintf('certificate/exchangerolls/%s/reject/%s', $r->cerid, $r->ciid));
				else
					$rows[$i-1][]='';
		}
		$user->content['cert']['certs']=array(
			'#type' => 'user_profile_item',
			'#title' => t('Applied certificates exchange'),
			'#markup'=>theme('table',array('header'=>$header, 'rows'=>$rows))
		);
	}
}

function cert_issue_massiveupload_query_form($form, $form_state) {
	$form['citera']=array(
		'#type' => 'fieldset',
		'#title' => t('Search citera'),
		'#collapsible' => TRUE,
		'#collapsed' => !empty($form_state['storage'])
	);
	$form['citera']['name']=array(
		'#type' => 'textfield',
		'#title' => t('Real Name of the student'),
	);
	$form['citera']['certid']=array(
		'#type' => 'textfield',
		'#title' => t('Certificate Number'),
	);
	if(!empty($form_state['storage'])) {
		$query=db_select('certificates_issues','ci')->fields('ci')->orderBy('ci.claimedby','desc')->orderBy('ci.certid');
		$query->isNull('ci.cerid');
		$query->innerJoin('certificates_operations','co','ci.coid=co.coid');
		$query->innerJoin('operations','o','co.oid=o.oid');
		$query->innerJoin('certificates','c','co.cid=c.cid');
		$query->leftJoin('students','s','ci.claimedby=s.uid');
		$query->addExpression('o.name','oname');
		$query->addExpression('c.series','series');
		$query->addExpression('c.name','cname');
		$query->addExpression('s.uid','uid');
		$query->addExpression('s.name','sname');
		if(!empty($form_state['storage']['name']))
			$query->condition('ci.name',$form_state['storage']['name'].'%', 'LIKE');
		if(!empty($form_state['storage']['certid']))
			$query->condition('ci.certid', $form_state['storage']['certid']);
		$rdbo=$query->execute();
		$i=1;
		foreach($rdbo as $r) {
			if($i<=10)
				$rows[]=array(
					$r->oname,
					sprintf("%s<br/>%s",$r->series, $r->cname),
					$r->certid,
					$r->name,
					empty($r->uid)?t('None'):l($r->sname, 'user/'.$r->uid),
					empty($r->claimedby)?'':l(t('Revoke'), sprintf('certificate/massiveupload/revoke/%s/%s', $r->ciid, $r->claimedby))
				);
			$i++;
		}
		if($i>10) {
			$rows[]=array(
				array('data'=>t('There are !num more certificates matched. Please consider doing a more strict search.', array('!num'=>$i-10)), 'colspan'=>5),
			);
		}
		$header=array(
			t('Running Operations'),
			t('Certificate Specification'),
			t('Certificate Number'),
			t('Certificate Name'),
			t('Claimed by'),
			t('Operation')
		);
		if(empty($rows)) {
			$form['table']=array('#markup' => '<div>'.t('There is no certificates matching your citeras.').'</div>');
			$form['citera']['#collapsed']=FALSE;
		} else 
			$form['table']=array(
				'#markup' => theme('table', array('header'=>$header, 'rows'=>$rows)),
			);

	}
	$form['search']=array(
		'#type' => 'submit',
		'#value' => t('Search'),
		'#name' => 'search',
	);
	if(!empty($form_state['storage']))
		$form['clearall']=array(
			'#type' => 'submit',
			'#name' => 'clearall',
			'#value' => t('Clear all filters'),
		);
	return $form;

}

function cert_issue_massiveupload_query_form_submit($form, &$form_state) {
	if($form_state['triggering_element']['#name']=='search')
		if(empty($form_state['values']['name']) && empty($form_state['values']['certid']))
			return;
		else {
			$form_state['rebuild']=TRUE;
			$form_state['storage']['name'] = trim($form_state['values']['name']);
			$form_state['storage']['certid'] = trim($form_state['values']['certid']);
		}
}

function rollsview_load($cerid) {
	$cer=cer_load($cerid);
	if(!empty($cer) && $cer->status >0 ) return $cer;
	else return FALSE;
}

function cert_issue_exchange_rolls_view_form_title($cer) {
	return t('Details for exchanging @cname', array('@cname'=>$cer->cname));
}

function cert_issue_exchange_rolls_view_form($form, &$form_state, $cer) {
	$totalnum=db_query('SELECT count(*) FROM {certificates_issues} WHERE cerid=:cerid', array(':cerid'=>$cer->cerid))->fetchField();
	$form['total']=array(
		'#markup' => t('There are !num students who had applied exchanging this certificate.', array('!num'=>$totalnum))
	);
	$form_state['storage']['charge']=array(
		'module'=>'cert_issue',
		'account'=>'certexchange',
		'ordertitle'=>cert_issue_user_exchange_form_title($cer),
		'admin'=>TRUE,
	);
	$header=array(
		array('data'=>t('Real Name'), 'field'=>'claimedby'),
		array('data'=>t('IDCard Number'), 'field'=>'ci.idcard_number'),
		t('Original certificate ID'),
		array('data'=>t('Status / Operation'), 'field'=>'ci.status', 'sort'=>'desc'),
	);
	$query=db_select('certificates_issues','ci')->fields('ci')->condition('ci.cerid',$cer->cerid)
		->extend('TableSort')->orderByHeader($header)->extend('PagerDefault')->limit(10);
	$rdbo=$query->execute();
	$rows=array();
	unset($form_state['storage']['ciid']);
	foreach($rdbo as $r) {
		$student=student_load($r->claimedby);
		$certs=array();
		foreach($cer->cid_orig as $cid) {
			$cert=db_query('SELECT certid FROM {certificates_issues} WHERE claimedby=:uid AND status=0', array(':uid'=>$r->claimedby))
				->fetchObject();
			$certs[]=sprintf('%s: %s', $cer->cname_orig[$cid], empty($cert->certid)?('<span style="color:red">'.t('None').'</span>'):$cert->certid);
		}
		if(count($cer->cid_orig) > 1)
			$certs_str='<ul><li>'.implode($certs,'</li><li>').'</li></ul>';
		else
			$certs_str=$certs[0];

		$rows[]=array(
			l(
				sprintf('<img src="%s" style="vertical-align: middle; padding: 5px; width: 60px"/>%s',
					$student->picture, $student->name),
				'user/'.$r->claimedby,
				array('html'=>TRUE, 'attributes'=>array('title'=>t('Click for details')))),
			$r->idcard_number,
			$certs_str,
			$r->status==1?(_cert_issue_get_status_text($r->status).'<br/>'.l(t('Reject'), sprintf('certificate/exchangerolls/%d/reject/%d', $r->cerid, $r->ciid))):_cert_issue_get_status_text($r->status),
		);
		if($r->status)
			$form_state['storage']['ciid'][]=$r->ciid;
	}
	$form['table']=array(
		'#markup' => theme('table', array('header'=>$header, 'rows'=>$rows, 'empty'=>t('There are no students to display.')))
	);
	if(!empty($rows)) {
		if(!empty($form_state['storage']['ciid'])) {
			$form['confirm']=array(
				'#type' => 'submit',
				'#weight' => 99,
				'#value' => t('Mark all applications in this page as approved'),
			);
		}
		$form['pager']=array('#markup'=>theme('pager'));
	}
	return $form;
}

function cert_issue_exchange_rolls_view_form_submit($form, &$form_state) {
	$i=0;
	foreach($form_state['storage']['ciid'] as $ciid)
		$i+=db_update('certificates_issues')->condition('ciid',$ciid)->fields(array(
			'status' => 0
		))->execute();
	if($i) {
		drupal_set_message(t('Approved !num students applications.', array('!num'=>$i)));
		watchdog('user',
			'Approved !num students applications.', array(
				'!num'=>$i,
				),
			WATCHDOG_INFO
		);
	}
}

function certissue_load($ciid) {
	return db_query('SELECT ci.*, c.name AS cname, c.series AS series, o.name AS oname FROM {certificates_issues} ci '.
		'INNER JOIN {certificates_operations} co ON ci.coid=co.coid '.
		'INNER JOIN {certificates} c ON c.cid=co.cid '.
		'INNER JOIN {operations} o ON o.oid=co.oid '.
		'WHERE ciid=:ciid',
		array(':ciid'=>$ciid))->fetchObject();
}

function cert_issue_revoke_cert_form_access($cert, $student) {
	if(user_access('preload certificates') && $cert->claimedby==$student->uid) return TRUE;
	else return FALSE;
}

function cert_issue_revoke_cert_form($form, &$form_state, $cert, $student) {
	if($cert->claimedby!=$student->uid) return NULL;
	$title=t('About to revoke certificate No.!certid', array('!certid'=>$cert->certid));
	$form_state['storage']['ciid']=$cert->ciid;
	$form_state['storage']['certid']=$cert->certid;
	$form_state['storage']['uid']=$student->uid;
	$form['certname']=array(
		'#type' => 'item',
		'#title' => t('Specification'),
		'#markup' => sprintf('%s %s', $cert->series, $cert->cname)
	);
	$form['org']=array(
		'#type' => 'item',
		'#title' => t('Organization'),
		'#markup' => $cert->oname
	);
	$form['name']=array(
		'#type' => 'item',
		'#title' => t('Name on certificate'),
		'#markup' => t('!name (!gender, birth date: !birth)',
			array('!name'=>$cert->name,
				'!gender'=>$cert->gender==1?t('Male'):t('Female'),
				'!birth'=>$cert->date_of_birth)
			),
	);
	$form['student']=array(
		'#type' => 'item',
		'#title' => t('Claimed by'),
		'#markup' => t('!name (!gender, birth date: !birth)',
			array('!name'=>$student->name,
				'!gender'=>((empty($student->exname)?'':t('Exname !exname,',array('!exname'=>$student->exname)))).($student->gender==1?t('Male'):t('Female')),
				'!birth'=>$student->date_of_birth)
			),
	);
	$form['redirect']=array(
		'#type' => 'hidden',
		'#value'=> empty($_SERVER['HTTP_REFERER'])?'certificate/massiveupload/query':$_SERVER['HTTP_REFERER'],
	);
	return confirm_form($form,
		$title,
		empty($_SERVER['HTTP_REFERER'])?'certificate/massiveupload/query':$_SERVER['HTTP_REFERER'],
		t('If the student has applied cert exchange based on this certificate, the request will not be rejected automatically.'),
		t('Revoke')
	);
}

function cert_issue_revoke_cert_form_submit($form, &$form_state) {
	$cert=certissue_load($form_state['storage']['ciid']);
	$r=db_update('certificates_issues')->condition('ciid',$form_state['storage']['ciid'])
		->condition('claimedby', $form_state['storage']['uid'])->fields(array(
			'claimedby' => 0
		))->execute();
	if($r) {
		drupal_set_message(t('Certificate No.!no is revoked.', array('!no'=>$form_state['storage']['certid'])));
		watchdog('certificate',
			'Revoked !cname certificate !certid of !user.', array(
				'!user'=>$cert->name,
				'!cname'=>$cert->cname,
				'!certid'=>$cert->certid
				),
			WATCHDOG_INFO
		);
	}
	$form_state['redirect']=$_POST['redirect'];
}

function cert_issue_exchange_rolls_reject_form_access($cer, $cert) {
	if(user_access('admin certificates exchange rolls') && $cert->cerid==$cer->cerid && $cert->status == 1) return TRUE;
	return FALSE;
}

function cert_issue_exchange_rolls_reject_form($form, &$form_state, $cer, $cert) {
	$student=student_load($cert->claimedby);
	$form_state['storage']['uid']=$cert->claimedby;
	$form_state['storage']['ciid']=$cert->ciid;
	$form_state['storage']['cerid']=$cer->cerid;
	$form_state['storage']['name']=$student->name;
	$form_state['storage']['cname']=$cert->cname;
	$form_state['storage']['charge']=array(
		'module'=>'cert_issue',
		'account'=>'certexchange',
		'ordertitle'=>cert_issue_user_exchange_form_title($cer),
		'admin'=>TRUE,
	);
	$title=t('About to reject !name\'s !cname certificate exchange request', array('!name'=>$student->name, '!cname'=>$cert->cname));
	$form['name']=array(
		'#type' => 'item',
		'#title' => t('Real Name'),
		'#markup' => $cert->name,
		'#prefix' => sprintf('<img src="%s" height="80" align="left" style="margin-right: 20px; margin-bottom: 10px;"/>', $student->picture),
		'#weight' => -1,
	);
	$form['gender']=array(
		'#type' => 'item',
		'#title' => t('Gender'),
		'#markup' => $cert->gender==1?t('Male'):t('Female'),
		'#weight' => 0,
	);
	$certs=array();
	foreach($cer->cid_orig as $cid) {
		$cert=db_query('SELECT certid FROM {certificates_issues} WHERE claimedby=:uid AND status=0', array(':uid'=>$cert->claimedby))
			->fetchObject();
		$certs[]=sprintf('%s: %s', $cer->cname_orig[$cid], empty($cert->certid)?('<span style="color:red">'.t('None').'</span>'):$cert->certid);
	}
	if(count($cer->cid_orig) > 1)
		$certs_str='<ul><li>'.implode($certs,'</li><li>').'</li></ul>';
	else
		$certs_str=$certs[0];
	$form['orig_cert']=array(
		'#type' => 'item',
		'#title' => t('Original certificate ID'),
		'#markup' => $certs_str,
		'#weight' => 1,
	);
	$form['redirect']=array(
		'#type' => 'hidden',
		'#value'=> empty($_SERVER['HTTP_REFERER'])?('certificate/exchangerolls/'.$cer->cerid):$_SERVER['HTTP_REFERER'],
	);
	return confirm_form($form,
		$title,
		empty($_SERVER['HTTP_REFERER'])?('certificate/exchangerolls/'.$cer->cerid):$_SERVER['HTTP_REFERER'],
		'',
		t('Reject')
	);
}

function cert_issue_exchange_rolls_reject_form_submit($form, &$form_state) {
	$cert=certissue_load($form_state['storage']['ciid']);
	$r=db_delete('certificates_issues')->condition('ciid',$form_state['storage']['ciid'])
		->execute();
	if($r) {
		drupal_set_message(t('!name\'s !cname certificate exchange request is rejected.', array('!name'=>$form_state['storage']['name'], '!cname'=>$form_state['storage']['cname'])));
		watchdog('certificate',
			'Rejected !cname exchange request of !user.', array(
				'!user'=>$cert->name,
				'!cname'=>$cert->cname,
				),
			WATCHDOG_INFO
		);
	}
	$form_state['redirect']=$_POST['redirect'];;
}

function cert_issue_form_certificate_specification_form_alter(&$form, &$form_state) {
	foreach(element_children($form['existing']) as $key) {
		if(preg_match('/^delete/',$key)) {
			$cid=substr($key,6);
			$a=db_query('SELECT EXISTS(SELECT * FROM {certificates_operations} WHERE cid=:cid)', array(':cid'=>$cid))->fetchField();
			if($a)
				$form['existing'][$key]=array('#markup'=>'');
		}
	}
}

/**
 * Implementation of hook_charge_accounts().
 */
function cert_issue_charge_accounts() {
	return array(
		'certexchange' => 'Cert Exchange',
	);
}

function cert_issue_user_delete($user) {
	$query=db_query('SELECT EXISTS(SELECT * FROM {certificates_issues} WHERE claimedby=:uid)', array(':uid'=>$user->uid));
	if($query->fetchField())
		throw new Exception(t("Cannot delete user !user, as there are certificates claimed by him.", array('!user'=>$user->name)));
}

?>
