<?php

define('charge_PAYMENT_SUCCESS', 1);
define('charge_PAYMENT_PROCESSING', 0);
define('charge_PAYMENT_FAILED', -1);
define('charge_PAYMENT_INVALID', -2);

/**
 * Implementation of hook_requirements().
 */
function charge_requirements($phase) {
	$requirements = array(); 

	if ($phase == 'runtime') {
		$t = get_t();
		$num=db_select('orders','o')->fields('o')->countQuery()->execute()->fetchField();
		$succeeded=db_select('orders','o')->fields('o')->condition('o.status',100)->countQuery()->execute()->fetchField();
		$requirements['onlinecharge'] = array(
			'title' => t('Online Charging orders'),
			'severity' => REQUIREMENT_INFO,
			'value' => t('@num orders have been created, and @succeeded of them succeeded', array('@num' => number_format($num), '@succeeded'=>number_format($succeeded))),
		);
	}
	return $requirements;
}

/**
 * Implements hook_help().
 */
function charge_help($path, $arg) {
	switch ($path) {
		case 'charge/fee':
			$output = t('Define charging fees and standard.');
			break;
		case 'charge/log':
			$output = t('Check payment logs.');
			break;
		case 'user/payment':
			$output = '<p>'.t('This page will list all your online payment orders.').'</p>';
			break;
		default:
			return;
	}
	return '<p>'.$output.'</p>';
}

/**
 * Implements hook_permission
 */
function charge_permission() {
	return array(
		'administer charging' => array(
			'title' => t('Administrater charging fees and view logs'),
		),
		'use online charging' => array(
			'title' => t('Use online charging feature'),
		),
	);
}

function charge_theme() {
	return array(
		'charge_fee' => array(
			'render element' => 'form', 
		),
		'charge_user_orders' => array(
			'render element' => 'form', 
		),
		'charge_log_form' => array(
			'render element' => 'form', 
		),
	);
}

/**
 * Implements hook_menu().
 */
function charge_menu() {
	$items['charge'] = array(
		'title' => 'Online charging',
		'description' => "Features regarding online charging.",
		'page callback' => 'charge_admin_page',
		'access callback' => 'user_access',
		'access arguments' => array('administer charging'),
		'expanded' => TRUE,
	);
	$items['charge/fee'] = array(
		'title' => 'Fees',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('charge_fee'),
		'weight' => 1,
		'description' => "Define charging fees and standard.",
		'access callback' => 'user_access',
		'access arguments' => array('administer charging'),
	);
	$items['charge/log'] = array(
		'title' => 'Payment Logs',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('charge_log_form'),
		'weight' => 2,
		'description' => "Check payment logs.",
		'access callback' => 'user_access',
		'access arguments' => array('administer charging'),
	);
	$items['user/payment'] = array(
		'title' => 'Charging Center',
		'menu_name' => 'user-menu',
		'plid' => '0',
		'weight' => -10,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('charge_user_orders'),
		'access callback' => 'charge_user_access',
	);
	return $items;
}

function charge_admin_page() {
	$item = menu_get_item();
	$content = system_admin_menu_block($item);
	return theme('admin_block_content', array('content' => $content));
}

/**
 * Implements hook_block_info().
 */
function charge_block_info() {
	$result=array();
	
	$result['gateways'] = array(
		'info' => t('Supported Gateways'),
		'cache' => DRUPAL_CACHE_GLOBAL,
	);
	return $result;
}

/**
 * Implements hook_block_view().
 */
function charge_block_view($delta = '') {
	global $user;
	$block = array();
	switch ($delta) {
		case 'gateways':
			$block['subject'] = t('Supported Gateways');
			$gateways=module_invoke_all('paymentgatewayinfo');
			$options=array();
			foreach($gateways as $k => $v) {
				if(module_hook($k, 'submit_form_submit'))
					if(is_array($v))
						$options[$k]=sprintf('<a href="%s" target="_blank"><img src="/%s"/></a>', $v['url'], $v['front']);
					else
						$options[$k]='<img src="/'.$v.'"/>';
			}
			$block['content'] = '<div style="text-align: center">'.implode('<br/>',$options).'</div>';
			return $block;
			break;
  		}
}

function charge_fee($form, &$form_state) {
	$form=array();
	$modules=array();
	$accounts=array();
	foreach(module_implements('charge_accounts') as $module) {
		$modules[]=$module;
		$accounts[$module]=module_invoke($module, 'charge_accounts');
	}
	$form['modules']=array('#type'=>'hidden', '#value'=>json_encode($modules));
	$form['accounts']=array('#type'=>'hidden', '#value'=>json_encode($accounts));
	foreach($modules as $module) {
		foreach($accounts[$module] as $key=>$value) {
			$form[$module.'_'.$key]=array(
				'#type' => 'textfield',
				'#title' => 'RMB',
				'#description' => t($value),
				'#title_display' => 'after',
				'#required' => TRUE,
				'#size' => 10,
				'#default_value' => db_query('SELECT amount FROM {charging_accounts} WHERE module=:module AND account=:account',
					array(':module'=>$module, ':account'=>$key))->fetchField(),
				'#maxlength' => 10,
				'#attributes' => array('class'=>array('numeric'), 'style'=>array('text-align: right;')),
			);
		}
	}
	$form['save']=array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	return $form;
}

function theme_charge_fee($variables) {
	$form=$variables['form'];
	$output='';
	$header=array(
		t('Charging account'),
		t('Amount'),
	);
	$rows=array();
	$accounts=json_decode($form['accounts']['#value']);
	foreach($accounts as $module => $account) {
		foreach($account as $key=>$value) {
			$description=$form[$module.'_'.$key]['#description'];
			unset($form[$module.'_'.$key]['#description']);
			$rows[]=array(
				$description,
				drupal_render($form[$module.'_'.$key]),
			);
		}
	}
	$output.=theme('table', array('header'=>$header,'rows'=>$rows));
	unset($form['modules']);
	unset($form['accounts']);
	$output.=drupal_render_children($form);
	return $output;
}

function charge_fee_validate($form, $form_state) {
	foreach($form_state['values'] as $key => $value) {
		if(isset($form[$key]['#type']) && $form[$key]['#type']=='textfield') {
			var_dump($value);
			if(!preg_match('/^[0-9]+$/',$value))
				form_set_error($key, t('!field is not a valid integer value.',array('!field'=>$form[$key]['#description'])));
		}
	}
}

function charge_fee_submit($form, $form_state) {
	$accounts=json_decode($form['accounts']['#value']);
	foreach($accounts as $module => $account) {
		foreach($account as $key=>$value) {
			db_merge('charging_accounts')->key(array('module'=>$module, 'account'=>$key))->fields(array(
				'module'=>$module,
				'account'=>$key,
				'amount'=>$form_state['values'][$module.'_'.$key]
			))->execute();
		}
	}
	drupal_set_message(t('Charging accounts saved.'));
}

function charge_form_cert_issue_exchange_rolls_form_alter(&$form, &$form_state) {
	$form['addrolls']['#description']=t('Current charge amount: &yen;!num.', array(
		'!num' => number_format(db_query('SELECT amount FROM {charging_accounts} WHERE module=\'cert_issue\' AND account=\'certexchange\'')->fetchField()))
	);
	if(user_access('administer charging'))
		$form['addrolls']['#description'].=l(t('Modify?'),'charge/fee');
}

function charge_user_access() {
	if($GLOBALS['user']->uid==0) return FALSE;
	return (db_query('SELECT EXISTS( SELECT * FROM {orders} WHERE uid=:uid)', array(':uid'=>$GLOBALS['user']->uid))->fetchField());
}

function charge_form_alter(&$form, &$form_state, $form_id) {
	if(isset($form_state['storage']['charge'])) {
		$form['#submit'][]='charge_form_alter_submit';
	}
}

function charge_form_alter_submit(&$form, &$form_state) {
	$obj=db_query('SELECT * FROM {charging_accounts} WHERE module=:module AND account=:account',
		array(':module'=>$form_state['storage']['charge']['module'],':account'=>$form_state['storage']['charge']['account']))
		->fetchObject();
	if(!$obj) return;
	$r=db_merge('orders')->key(array('uid'=>$GLOBALS['user']->uid, 'ordertitle'=>$form_state['storage']['charge']['ordertitle']))
		->insertFields(array(
		'orderno' => sprintf('%s%06d',date('YmdHms'),mt_rand(0,999999)),
		'uid' => $GLOBALS['user']->uid,
		'ordertime' => time(),
		'standard' => $obj->caid,
		'ordertitle' => $form_state['storage']['charge']['ordertitle'],
		'amount' => $obj->amount,
		'status' => $obj->amount > 0,
	))->execute();
	if($r) {
		$form_state['redirect']='user/payment';
		drupal_set_message(t('Unpaid order generated.'));
	}
}

function charge_user_orders($form, $form_state) {
	$user=$GLOBALS['user'];
	$rdbo=db_query('SELECT * FROM {orders} WHERE uid=:uid ORDER BY ordertime',array(':uid'=>$user->uid));
	$form=array();
	$orders=array();
	foreach($rdbo as $r) {
		$orders[]=$r->orderno;
		$form['order_'.$r->orderno]=array(
			'#type' => 'fieldset',
		);
		$form['order_'.$r->orderno]['orderno']=array(
			'#type' => 'item',
			'#markup' => $r->orderno,
		);
		$form['order_'.$r->orderno]['ordertitle']=array(
			'#type' => 'item',
			'#markup' => $r->ordertitle,
		);
		$form['order_'.$r->orderno]['amountdue']=array(
			'#type' => 'item',
			'#markup' => sprintf('&yen;%d', $r->amount),
		);
		switch ($r->status) {
			case 100:
				$form['order_'.$r->orderno]['operation']=array(
					'#type' => 'markup',
					'#markup' => t('Succeeded'),
				);
				break;
			case 0:
				$form['order_'.$r->orderno]['operation']=array(
					'#type' => 'submit',
					'#name' => 'paybutton_'.$r->orderno,
					'#value' => t('Pay'),
				);
		}
		$process=db_query('SELECT amount FROM {orders_process} WHERE orderno=:orderno AND amount<>0 ORDER BY timestamp',
			array(':orderno'=>$r->orderno));
		$totaltext='';
		$totalamount=0;
		foreach($process as $p) {
			$totalamount+=$p->amount;
			if($p->amount>0)
				$totaltext.='+';
			$totaltext.=$p->amount;
		}
		if(substr($totaltext,0,1)=='+') $totaltext=substr($totaltext, 1);
		$form['order_'.$r->orderno]['totalamount']=array(
			'#type' => 'markup',
			'#markup' => empty($totaltext)?'':
				($totalamount==$r->amount?sprintf('&yen;%d', $r->amount):sprintf('&yen;%s (%s)',$totalamount,$totaltext)),
		);
	}
	$form['#description']=json_encode($orders);

	$gateways=module_invoke_all('paymentgatewayinfo');
	$options=array();
	foreach($gateways as $k => $v) {
		if(module_hook($k, 'submit_form_submit'))
			if(is_array($v))
				$options[$k]='<img src="/'.$v['payment'].'"/>';
			else
				$options[$k]='<img src="/'.$v.'"/>';
	}
	if(count($gateways)==1) {
		$keys=array_keys($options);
		$form['gateway']=array(
			'#type' => 'hidden',
			'#value' => $keys[0],
		);
		$form['gatewayintro']=array(
			'#type' => 'item',
			'#title' => t('Payment Gateway'),
			'#required' => TRUE,
			'#markup' => $options[$keys[0]],
			'#description' => t('We only support above payment gateway now.'),
		);
	} else {
		$form['gateway']=array(
			'#type' => 'radios',
			'#title' => t('Payment Gateway Selection'),
			'#description' => t('Please select your preferred payment gateway.'),
			'#required' => TRUE,
			'#options' => $options,
			'#attached' => array(
				'css' => array(drupal_get_path('module', 'charge') . '/onlinecharge.css'),
			),
		);
		$keys=array_keys($gateways);
		$form['gateway']['#default_value']=$keys[0];
	}
	foreach($gateways as $key => $value) {
		$form['help-'.$key]=array(
			'#type' => 'item',
			'#markup' => module_invoke($key, 'help', 'charge/'.$key, ''),
			'#states' => array(
				'visible' => array(
					'input[name="gateway"]' => array('value' =>$key),
				),
			),
		);
	}
	return $form;
}

function charge_generate_random_orderno() {
}

function charge_user_orders_validate($form, $form_state) {
}

function charge_user_orders_submit($form, $form_state) {
	$_form_state=array();
	$element=explode('_',$form_state['triggering_element']['#name']);
	$orderno=$element[1];
	$order=db_query('SELECT * FROM {orders} WHERE orderno=:orderno',array(':orderno'=>$orderno))->fetchObject();
	$student=student_load($GLOBALS['user']);
	$_form_state['values']=array(
		'orderno' => $order->orderno,
		'amount' => $order->amount,
		'ordertime' => $order->ordertime,
		'ordertitle' => sprintf('%s %s', student_load($GLOBALS['user'])->name, $order->ordertitle),
	);
	$output=module_invoke($form_state['values']['gateway'], 'submit_form_submit', $form, $_form_state);
	echo($output);
	exit;
}

function theme_charge_user_orders($variables) {
	$form=$variables['form'];
	$output='';
	$header=array(
		t('Order no'),
		t('Order title'),
		t('Amount due'),
		t('Transaction amount'),
		t('Operation')
	);
	$orders=json_decode($form['#description']);
	unset($form['#description']);
	$rows=array();
	foreach($orders as $order) {
		$rows[]=array(
			drupal_render($form['order_'.$order]['orderno']),
			drupal_render($form['order_'.$order]['ordertitle']),
			drupal_render($form['order_'.$order]['amountdue']),
			drupal_render($form['order_'.$order]['totalamount']),
			drupal_render($form['order_'.$order]['operation']),
		);
		unset($form['order_'.$order]);
	}

	$output.=theme('table',array('header'=>$header, 'rows'=>$rows));
	$output.=drupal_render_children($form);
	return $output;
}

function _charge_status_text($status) {
	switch($status) {
		case 0:
			return t('Not paid');
		case 10:
		case 11:
		case 12:
		case 13:
		case 14:
		case 15:
			return t('Processing');
		case 100:
			return t('Paid successful');
	}
}

function charge_gatewayreponse($params) {
	$gateways=array_keys($params);
	$gateway=$gateways[0];
	$orderno=$params[$gateway]['orderno'];
	$query=db_query('SELECT EXISTS (SELECT * FROM {orders} WHERE orderno=:orderno AND status <>100)', array(
		':orderno' => $orderno,
	));
	if($query->fetchField() && $params[$gateway]['is_backend']) {
		$r=db_insert('orders_process')->fields(array(
			'orderno' => $orderno,
			'timestamp' => time(),
			'gateway' => $gateway,
			'transno' => $params[$gateway]['transactionno'],
			'amount' => $params[$gateway]['amount']
		))->execute();
		$amount=db_query(
			'SELECT o.amount, SUM(op.amount) as opamount FROM {orders} o LEFT JOIN {orders_process} op ON o.orderno=op.orderno '.
			'WHERE o.orderno=:orderno GROUP BY o.orderno', array(':orderno'=>$orderno))->fetchObject();
		if($amount->amount==$amount->opamount)
			db_update('orders')->condition('orderno', $orderno)->fields(array('status'=>100))->execute();
		if(!empty($params[$gateway]['echostr'])) {
			echo $params[$gateway]['echostr'];
			exit;
		}
	}
	if($params[$gateway]['is_backend']) exit;
	$order=db_query('SELECT * FROM {orders} WHERE orderno=:orderno', array(':orderno' => $orderno))->fetchObject();
	drupal_set_message(t('Paid successful for !ordertitle, with !amount.',array(
		'!ordertitle'=>$order->ordertitle,
		'!amount'=>$params[$gateway]['amount']
	)));
	drupal_goto(sprintf('%s/user/payment', base_path()));
}

function charge_log_form($form, $form_state, $pre_orderno=NULL) {
	if($pre_orderno) {
		charge_user_logout();
		$_COOKIE['Drupal_visitor_orders_orderno']=$pre_orderno;
		unset($_COOKIE['Drupal_visitor_orders_orderdate']);
		unset($_COOKIE['Drupal_visitor_orders_gateway']);
		unset($_COOKIE['Drupal_visitor_orders_status']);
	}
	$form=array();
	$form['conditions']=array(
		'#type' => 'vertical_tabs',
	);
	$form['user']=array(
		'#type' => 'fieldset',
		'#title' => t('Search by User'),
		'#group'=>'conditions',
		'#attached' => array(
			'js' => array(drupal_get_path('module', 'onlinecharge') . '/onlinecharge.js'),
			'css' => array(drupal_get_path('module', 'onlinecharge') . '/onlinecharge.css'),
		),
		'#attributes' => array('class' => array('chargelogsearchbyuser')),
	);
	if(!isset($_COOKIE['Drupal_visitor_user_uid']))
		$_COOKIE['Drupal_visitor_user_uid']='';
	$form['user']['uid']=array(
		'#type' => 'textfield',
		'#title' => t('Student ID'),
		'#maxlength' => 10,
		'#size' => 30,
		'#default_value' => $_COOKIE['Drupal_visitor_user_uid'],
		'#attributes'=>array('placeholder'=>variable_get('zhaoban_current_year',date('Y')).'BXXXX'),
	);
	if(!isset($_COOKIE['Drupal_visitor_user_username']))
		$_COOKIE['Drupal_visitor_user_username']='';
	$form['user']['username']=array(
		'#type' => 'textfield',
		'#title' => t('Real Name'),
		'#maxlength' => 10,
		'#size' => 30,
		'#default_value' => $_COOKIE['Drupal_visitor_user_username'],
	);
	$form['orders']=array(
		'#type' => 'fieldset',
		'#title' => t('Search by Order'),
		'#group'=>'conditions',
		'#attached' => array(
			'js' => array(drupal_get_path('module', 'onlinecharge') . '/onlinecharge.js'),
		),
	);
	if(!isset($_COOKIE['Drupal_visitor_orders_orderno']))
		$_COOKIE['Drupal_visitor_orders_orderno']='';
	$form['orders']['orderno']=array(
		'#type' => 'textfield',
		'#title' => t('Order No.'),
		'#maxlength' => 20,
		'#size' => 10,
		'#default_value' => $_COOKIE['Drupal_visitor_orders_orderno'],
	);
	$query=db_select('orders','o')->fields('o',array('gatewaysettledate'))->isNotNull('o.gatewaysettledate');
	$query->distinct()->orderBy('gatewaysettledate');
	$result=$query->execute();
	$options=array(
		'00000000' => '-- '.t('All').' --',
	);
	foreach($result as $r) {
		$options[$r->gatewaysettledate]=intval(substr($r->gatewaysettledate,0,2)).t('Month').intval(substr($r->gatewaysettledate,2,2)).t('Day');
	}
	if(!isset($_COOKIE['Drupal_visitor_orders_orderdate']))
		$_COOKIE['Drupal_visitor_orders_orderdate']='00000000';
	$form['orders']['orderdate']=array(
		'#type' => 'select',
		'#title' => t('Order Settle Date'),
		'#options' => $options,
		'#default_value' => $_COOKIE['Drupal_visitor_orders_orderdate'],
	);
	if(!isset($_COOKIE['Drupal_visitor_orders_gateway']))
		$_COOKIE['Drupal_visitor_orders_gateway']='0';
	$options=array(
		'0'=>'-- '.t('All').' --',
		'offline' => t('Offline'),
	);
	$gateways=module_invoke_all('paymentgatewayinfo');
	foreach($gateways as $k => $v) {
		if(module_hook($k, 'submit_form_submit'))
			$options[$k]=t($k);
	}
	$form['orders']['ordergateway']=array(
		'#type' => 'select',
		'#title' => t('Payment Gateway'),
		'#options' => $options,
		'#default_value' => $_COOKIE['Drupal_visitor_orders_gateway'],
	);
	if(!isset($_COOKIE['Drupal_visitor_orders_status']))
		$_COOKIE['Drupal_visitor_orders_status']='-1';
	$form['orders']['status']=array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#options' => array(
			'-1' => '-- '.t('All').' --',
			'0' => t('Not paid'),
			'10' => t('Processing'),
			'100' => t('Paid successful'),
		),
		'#default_value' => $_COOKIE['Drupal_visitor_orders_status'],
	);
	$form['submit']=array(
		'#type' => 'submit',
		'#value' => t('Search'),
		'#name' => 'search',
	);
	$form['clearall']=array(
		'#type' => 'submit',
		'#value' => t('Clear all filters'),
		'#name' => 'clearall',
		'#attributes' => array('title' => t('So that all the filters could be reset')),
	);
	$header=array(
		'suid' => array('data' => t('Student ID'), 'field'=> 'suid'),
		'name' => array('data' => t('Real Name'), 'field'=> 'sname'),
		'ordertitle' => array('data' => t('Order Title'), 'field'=> 'ordertitle'),
		'orderno' => array('data' => t('Order No'), 'field'=> 'orderno', 'sort'=>'desc'),
		'gateway' => array('data' => t('Gateway'), 'field'=> 'gateway'),
		'transno' => array('data' => t('Transaction No'), 'field'=> 'gatewaytransactionno'),
		'status' => array('data' => t('Status'), 'field'=> 'status'),
		'operation' => array('data' => t('Operation')),
	);
	
	$query=db_select('orders','o');
	$query->innerJoin('vl_charging_standard','sc','o.standard=sc.scid');
	$query->innerJoin('users','u','u.uid=o.uid');
	$query->innerJoin('students','s','s.uid=u.name');

	if(!empty($_COOKIE['Drupal_visitor_user_uid']))
		$query->condition('s.uid',$_COOKIE['Drupal_visitor_user_uid']);
	if(!empty($_COOKIE['Drupal_visitor_user_username']))
		$query->condition('s.name',$_COOKIE['Drupal_visitor_user_username']);
	if(!empty($_COOKIE['Drupal_visitor_orders_orderno']))
		$query->condition('o.orderno',$_COOKIE['Drupal_visitor_orders_orderno']);
	if($_COOKIE['Drupal_visitor_orders_gateway']!='0')
		$query->condition('o.gateway',$_COOKIE['Drupal_visitor_orders_gateway']);
	if($_COOKIE['Drupal_visitor_orders_orderdate']!='00000000')
		$query->condition('o.gatewaysettledate',$_COOKIE['Drupal_visitor_orders_orderdate']);
	if($_COOKIE['Drupal_visitor_orders_status']!='-1')
		if($_COOKIE['Drupal_visitor_orders_status']=='10')
			$query->condition('o.status','10','>=')->condition('o.status','100','<>');
		else
			$query->condition('o.status',$_COOKIE['Drupal_visitor_orders_status']);
	$amountq=clone $query;
	$amountq->addExpression('1');
	$transnum=$amountq->execute()->rowCount();
	$amountq->addExpression('SUM(o.amount)','amountq');
	$amount=$amountq->execute()->fetchField(1);
	if($transnum > 0)
		$form['summary']=array(
			'#markup' => '<b>'.t('Based on current conditions, @num transactions were found, and the related amount is @amount.',array('@num'=>$transnum, '@amount'=>number_format($amount))).'</b>',
		);
	$query->addExpression('s.uid','suid');
	$query->fields('o')->fields('sc',array('period'));
	$query->addExpression('CONVERT(s.name USING gbk)', 'sname');
	$query=$query->extend('PagerDefault')->limit(10)->extend('TableSort')->orderByHeader($header);
	$result=$query->execute();
	$form['orderlist']=array(
		'#type'=>'fieldset',
	);
	foreach($result as $r) {
		$form['orderlist'][$r->orderno]=array(
			'#type'=>'fieldset',
		);
		$form['orderlist'][$r->orderno]['suid']=array(
			'#markup' => l($r->suid, sprintf('user/%s',$r->uid)),
		);
		$form['orderlist'][$r->orderno]['sname']=array(
			'#markup' => $r->sname,
		);
		$form['orderlist'][$r->orderno]['orderno']=array(
			'#markup' => $r->orderno,
		);
		$form['orderlist'][$r->orderno]['ordertime']=array(
			'#markup' => date(t('nMonthjday'),$r->ordertime),
		);
		$form['orderlist'][$r->orderno]['ordertitle']=array(
			'#markup' => sprintf("%s (&yen;%s)", $r->period==1?t('1st round'):($r->period==2?t('2nd round'):t('3rd round')), $r->amount),
		);
		$form['orderlist'][$r->orderno]['gateway']=array(
			'#markup' => $r->gateway=='offline'?t('Offline'):$r->gateway,
		);
		$form['orderlist'][$r->orderno]['gatewaytransactionno']=array(
			'#markup' => $r->gatewaytransactionno,
		);
		if(!empty($r->gatewaysettledate))
			$form['orderlist'][$r->orderno]['gatewaysettledate']=array(
				'#markup' => intval(substr($r->gatewaysettledate,0,2)).t('Month').intval(substr($r->gatewaysettledate,2,2)).t('Day'),
			);
		$form['orderlist'][$r->orderno]['status']=array(
			'#markup' => _charge_status_text($r->status),
		);
		switch($r->status) {
			case 0:
				$form['orderlist'][$r->orderno]['payoffline']=array(
					'#type' => t('submit'),
					'#name' => 'payoffline'.$r->orderno,
					'#value' => t('Paid offline'),
				);
				break;
			case 10:
			case 11:
			case 12:
			case 13:
			case 14:
			case 15:
				if(module_hook($r->gateway, 'querystatus')) {
					$form['orderlist'][$r->orderno]['requery']=array(
						'#type' => t('submit'),
						'#name' => 'requery'.$r->orderno,
						'#value' => t('Query status'),
						'#attributes' => array('title' => t('Use online interface to query the status of specific order')),
					);
				}
				$form['orderlist'][$r->orderno]['setfailed']=array(
					'#type' => t('submit'),
					'#name' => 'setfail'.$r->orderno,
					'#value' => t('Set as unpaid'),
					'#attributes' => array('title' => t('Force set the order as unpaid, and regenerate the orderno. Please do this AFTER relative operations in payment gateway.')),
				);
				break;
			case 100:
		}
	}
	return $form;
}

function theme_charge_log_form($variables) {
	$form=$variables['form'];
	$output='';
	$output.=drupal_render($form['conditions']);
	$output.=drupal_render($form['user']);
	$output.=drupal_render($form['orders']);
	$output.=drupal_render($form['submit']);
	$output.=drupal_render($form['clearall']);
	$output.='<p>';
	$output.=drupal_render($form['summary']);
	$output.='</p>';
	$header=array(
		'suid' => array('data' => t('Student ID'), 'field'=> 'suid'),
		'name' => array('data' => t('Real Name'), 'field'=> 'sname'),
		'ordertitle' => array('data' => t('Order Title'), 'field'=> 'ordertitle'),
		'orderno' => array('data' => t('Order No.'), 'field'=> 'orderno', 'sort'=>'desc'),
		'status' => array('data' => t('Status'), 'field'=> 'status'),
		'operation' => array('data' => t('Operation')),
	);
	$rows=array();
	foreach($form['orderlist'] as $key => $value) {
		if(substr($key,1,1)=='#') continue;
		if(!is_array($value)) continue;
		if(!isset($value['#type'])) continue;
		if($value['#type']!='fieldset') continue;
		$orderno=drupal_render($form['orderlist'][$key]['orderno']);
		if($form['orderlist'][$key]['ordertime']['#markup'])
			$orderno.='<br/>'.t('Order submit date @date',array('@date'=>t(drupal_render($form['orderlist'][$key]['ordertime']))));
		if($form['orderlist'][$key]['gateway']['#markup'])
			$orderno.='<br/>'.t('Via @gateway',array('@gateway'=>t(drupal_render($form['orderlist'][$key]['gateway']))));
		if($form['orderlist'][$key]['gatewaytransactionno']['#markup'])
			$orderno.='<br/>'.t('Transno @transno',array('@transno'=>drupal_render($form['orderlist'][$key]['gatewaytransactionno'])));
		if(isset($form['orderlist'][$key]['gatewaysettledate']['#markup']))
			$orderno.='<br/>'.t('Settle Date @date',array('@date'=>drupal_render($form['orderlist'][$key]['gatewaysettledate'])));
		$rows[]=array(
			'suid' => drupal_render($form['orderlist'][$key]['suid']),
			'name' => drupal_render($form['orderlist'][$key]['sname']),
			'ordertitle' => drupal_render($form['orderlist'][$key]['ordertitle']),
			'orderno' => $orderno,
			'status' => drupal_render($form['orderlist'][$key]['status']),
			'operation' => drupal_render_children($form['orderlist'][$key]),
		);
		unset($form['orderlist'][$key]);
	}
	unset($form['orderlist']);
	$output .= theme('table', array('header'=>$header, 'rows'=>$rows, 'empty'=>t('No suitable orders.').t('Please check if you have set correct order status.')));
	$output.=drupal_render_children($form);
	$output .= theme('pager');
	return $output;
}

function charge_log_form_submit($form, &$form_state) {
	switch($form_state['triggering_element']['#name']) {
	case 'search':
		user_cookie_save(array(
			'user_uid' => trim($form_state['values']['uid']),
			'user_username' => trim($form_state['values']['username']),
			'orders_orderno' => trim($form_state['values']['orderno']),
			'orders_orderdate' => trim($form_state['values']['orderdate']),
			'orders_status' => trim($form_state['values']['status']),
			'orders_gateway' => trim($form_state['values']['ordergateway']),
		));
		break;
	case 'clearall':
		$cookies=array('user_uid', 'user_username', 'orders_orderno', 'orders_orderdate', 'orders_gateway', 'orders_status');
		foreach($cookies as $c) {
			user_cookie_delete($c);
		}
		break;
	default:
		if(preg_match('/^payoffline/', $form_state['triggering_element']['#name'])) {
			$orderno=substr($form_state['triggering_element']['#name'],-20);
			db_update('orders')->condition('orderno',$orderno)->fields(array(
				'gateway' => 'offline',
				'gatewaytransactionno' => NULL,
				'gatewaysettledate' => date('md'),
				'status' => 100
			))->execute();
			watchdog('onlinecharge',
				'@orderno payment succeeded offline.', array(
					'@orderno' => $orderno,
				),
				WATCHDOG_INFO,
				l(t('View'), 'charge/log/'.$orderno)
			);
			drupal_set_message(t('Order @orderno status updated.',array('@orderno'=>$orderno)));
			user_cookie_save(array(
				'orders_orderno' => $orderno,
			));
			user_cookie_delete('orders_orderdate');
			user_cookie_delete('orders_gateway');
			user_cookie_delete('orders_status');
		}
		if(preg_match('/^setfail/', $form_state['triggering_element']['#name'])) {
			$orderno=substr($form_state['triggering_element']['#name'],-20);
			db_update('orders')->condition('orderno',$orderno)->fields(array(
				'gateway' => NULL,
				'gatewaytransactionno' => NULL,
				'gatewaysettledate' => NULL,
				'status' => 0
			))->execute();
			$neworderno=charge_generate_random_orderno();
			db_update('orders')->condition('orderno',$orderno)->fields(array(
				'orderno' => $neworderno
			))->execute();
			watchdog('onlinecharge',
				'@orderno set as failed.', array(
					'@orderno' => $orderno,
				),
				WATCHDOG_INFO,
				l(t('View'), 'charge/log/'.$neworderno)
			);
			drupal_set_message(t('Order @orderno status updated. The new order number is @new.',array('@orderno'=>$orderno, '@new'=>$neworderno)), 'error');
			user_cookie_save(array(
				'orders_orderno' => $neworderno,
			));
			user_cookie_delete('orders_orderdate');
			user_cookie_delete('orders_gateway');
			user_cookie_delete('orders_status');
		}
		if(preg_match('/^requery/', $form_state['triggering_element']['#name'])) {
			$orderno=substr($form_state['triggering_element']['#name'],-20);
			$r=db_select('orders','o')->condition('o.orderno',$orderno)->fields('o')->execute()->fetchObject();
			$t=module_invoke($r->gateway, 'querystatus', $orderno, $r->ordertime);
			if(is_array($t)) {
				db_update('orders')->condition('orderno',$r->orderno)->fields(array(
					'gatewaytransactionno' => $t[$r->gateway]['transactionno'],
					'gatewaysettledate' => isset($t[$r->gateway]['settledate'])?$t[$r->gateway]['settledate']:date('md'),
					'status' => 100,
				))->execute();
				watchdog('onlinecharge',
					'@orderno payment succeeded via @gateway.', array(
						'@orderno' => $r->orderno,
						'@gateway' => $r->gateway
					),
					WATCHDOG_INFO,
					l(t('View'), 'charge/log/'.$r->orderno)
				);
				drupal_set_message(t('Order @orderno status updated.',array('@orderno'=>$orderno)));
				user_cookie_save(array(
					'orders_orderno' => $orderno,
				));
				user_cookie_delete('orders_orderdate');
				user_cookie_delete('orders_gateway');
				user_cookie_delete('orders_status');
			} else {
				if($t==charge_PAYMENT_INVALID || $t==charge_PAYMENT_FAILED ) {
					db_update('orders')->condition('orderno',$r->orderno)->fields(array(
						'gatewaytransactionno' => NULL,
						'gatewaysettledate' => NULL,
						'status' => 0,
					))->execute();
					drupal_set_message(t('Order @orderno process failed.',array('@orderno'=>$orderno)), 'error');
					watchdog('onlinecharge',
						'@orderno process failed via @gateway.', array(
							'@orderno' => $r->orderno,
							'@gateway' => $r->gateway
						),
						WATCHDOG_ERROR,
						l(t('View'), 'charge/log/'.$r->orderno)
					);
					user_cookie_save(array(
						'orders_orderno' => $orderno,
					));
					user_cookie_delete('orders_orderdate');
					user_cookie_delete('orders_gateway');
					user_cookie_delete('orders_status');
				} else {
					drupal_set_message(t('Order @orderno status is not updated.',array('@orderno'=>$orderno)), 'warning');
				}
			}
		}
	}
	drupal_goto('charge/log');
}

function charge_cron() {
	$result=db_select('orders','o')->condition('o.status','100','<>')->condition('o.status','0','<>')->isNotNull('o.gateway')->fields('o',array('orderno','gateway','status','ordertime'))->execute();
	if(!$result) return;
	foreach($result as $r) {
		if($r->status==15) {
			db_update('orders')->condition('orderno',$r->orderno)->fields(array(
				'gateway' => NULL,
				'gatewaytransactionno' => NULL,
				'gatewaysettledate' => NULL,
				'status' => 0,
			))->execute();
			watchdog('onlinecharge',
				'@orderno process failed via @gateway.', array(
					'@orderno' => $r->orderno,
					'@gateway' => $r->gateway
				),
				WATCHDOG_ERROR,
				l(t('View'), 'charge/log/'.$r->orderno)
			);
			continue;
		}
		// hook_querystatus returns array of transaction number, settledate, etc., if succeeded, or FALSE when failed.
		if(!module_hook($r->gateway, 'querystatus')) continue;
		$t=module_invoke($r->gateway, 'querystatus', $r->orderno, $r->ordertime);
		if(is_array($t)) {
			db_update('orders')->condition('orderno',$r->orderno)->fields(array(
				'gatewaytransactionno' => $t[$r->gateway]['transactionno'],
				'gatewaysettledate' => isset($t[$r->gateway]['settledate'])?$t[$r->gateway]['settledate']:date('md'),
				'status' => 100,
			))->execute();
			watchdog('onlinecharge',
				'@orderno payment succeeded via @gateway.', array(
					'@orderno' => $r->orderno,
					'@gateway' => $r->gateway
				),
				WATCHDOG_INFO,
				l(t('View'), 'charge/log/'.$r->orderno)
			);
		} else {
			$status=$r->status;
			if(($t==charge_PAYMENT_INVALID || $t==charge_PAYMENT_PROCESSING ) && time()-$r->ordertime >= 7200)
				$status=15;
			if($t==charge_PAYMENT_FAILED)
				$status=15;
			db_update('orders')->condition('orderno',$r->orderno)->fields(array(
				'status' => $status,
			))->execute();
			watchdog('onlinecharge',
				'@orderno process without success via @gateway.', array(
					'@orderno' => $r->orderno,
					'@gateway' => $r->gateway
				),
				WATCHDOG_WARNING,
				l(t('View'), 'charge/log/'.$r->orderno)
			);
		}
	}
}

function charge_user_logout() {
	$cookies=array('user_uid', 'user_username', 'orders_orderno', 'orders_orderdate', 'orders_gateway', 'orders_status');
	foreach($cookies as $c) {
		user_cookie_delete($c);
	}
}

function charge_user_login() {
	$cookies=array('user_uid', 'user_username', 'orders_orderno', 'orders_orderdate', 'orders_gateway', 'orders_status');
	foreach($cookies as $c) {
		user_cookie_delete($c);
	}
}

?>
