<?php

/*
 * This file is licensed under GPLv2+.
*/

function _student_genRandomString($len) 
{ 
	$chars = array( 
		"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",  
		"l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v",  
		"w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G",  
		"H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R",  
		"S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2",  
		"3", "4", "5", "6", "7", "8", "9" 
	); 
	$charsLen = count($chars) - 1; 

	shuffle($chars);

	$output = ""; 
	for ($i=0; $i<$len; $i++) 
	{ 
		$output .= $chars[mt_rand(0, $charsLen)]; 
	} 

	return $output; 

}

function _student_get_random_mail_address(){
	return _student_genRandomString(10).'@'._student_genRandomString(5).'.'._student_genRandomString(5).".com";
}

/**
* Function that determine whether YYYYMMDD is a valid date
*/
function _student_is_date_validate($datestr) {
	switch (strlen($datestr)) {
		case 8:
			$year = substr($datestr,0,4);
			$month = substr($datestr,4,2);
			$day = substr($datestr,6,2);
			return checkdate($month, $day, $year);
		default: return false;
	}
}

/**
* Function that computes the capthca char of IDCard number.
*/
function _student_idc_get_captcha($idcardn) {
	$idcardn = substr($idcardn, 0, 17);
	$sum = 0;
	$weight = array (7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2);
	for ($i=0; $i<17; $i++) {
		$sum += substr($idcardn, $i, 1)* $weight[$i];
	}
	$captcha = 12 - ($sum % 11);
	switch ($captcha) {
		case 10: $captcha = 'X'; break;
		case 11: $captcha = '0'; break;
		case 12: $captcha = '1'; break;
		default: $captcha = sprintf('%d',$captcha);
	}
	return $captcha;
}

function _student_is_idcardn_validate($idcardn) {
	switch (strlen($idcardn)) {
		case 18:
			if (preg_match('/\d{17}[\dX]/', $idcardn) == 0)
				return false;
			if (!_student_is_date_validate(substr($idcardn,6,8)))
				return false;
			if (_student_idc_get_captcha($idcardn) != substr($idcardn, 17, 1))
				return false;
			return true;
		default: return false;
	}
}


/**
 * @file
 * Defines the the progress of signup.
 */
 
/**
 * Implementation of hook_menu().
 */
function student_menu() {
	$items=array();
	$items['user/%user/%/picture.jpg'] = array(
		'page callback' => 'student_picture',
		'page arguments' => array(1,2),
		'type' => MENU_CALLBACK,
		'access callback' => 'student_picture_perm',
		'access arguments'=> array(1,2),
	);
	return $items;
}

function student_picture_perm($user,$rev=NULL) {
	if(!user_view_access($user)) return FALSE;
	return db_query('SELECT EXISTS(SELECT * FROM {students} WHERE uid=:uid AND picture=:rev)',array(':uid'=>$user->uid, ':rev'=>$rev));
}

function student_form_user_register_form_alter(&$form, &$form_state) {
	// we don't need email address for this site
	$form['account']['mail']['#type']='hidden';
	$form['account']['mail']['#value']=_student_get_random_mail_address();

	if(!user_access('administer users')) {
		$form['account']['name']['#description']=t('You may select any nick name you like for this.');
		$form['actions']['submit']['#value']=t('Register and Proceed');
		drupal_set_title(t('Register New Account'));
		$form['#submit'][] = 'student_form_user_register_form_submit';
	}
}

function student_form_user_register_form_submit($form, &$form_state) {
	$form_state['redirect'] = 'user/'.$form_state['uid'].'/edit';
	drupal_get_messages('error');
}

function student_form_user_profile_form_alter(&$form, $form_state) {
	if(!user_access('administer users'))
		$form['account']['current_pass']['#description']=t('Enter your current password to change the password.').t('If you forgot current password, <a href="@url">please click here</a> to reset password.', array('@url'=>'/user/password'));
	if($form['#user']->uid <> 1) {
		$form['account']['name']['#disabled'] = TRUE;
		$form['account']['status']['#disabled'] = TRUE;
		$form['account']['status']['#type'] = 'hidden';
		unset($form['actions']['cancel']);
	}
	if(isset($form['account']['mail']) && $form['#user']->uid <> 1)
		$form['account']['mail']['#type']='hidden';
	if(empty($form['#user']->mail)) {
		$mail=_student_get_random_mail_address();
		user_save($form['#user'], array('mail'=>$mail));
		$form['#user']->mail=$mail;
		$form['account']['mail']['#default_value']=$mail;
	}
	if($GLOBALS['user']->uid==1) return;
	if($GLOBALS['user']->uid == $form['#user']->uid || user_access('administer users'))
		student_user_account_form($form, $form_state);
}

function student_user_account_form(&$form, $form_state) {
	$user=$form['#user'];
	$form['account']['#type']='fieldset';
	$form['account']['#collapsible']=TRUE;
	$form['account']['#collapsed']=TRUE;
	$form['account']['#title'] = t('Change Password');

	$defaults=student_load($user);

	$form['personal'] = array(
		'#type' => 'fieldset',
		'#title' => t('Personal information'),
		'#description' => t('You\'ll need to provide these information when reseting password.'),
		'#collapsible' => TRUE,
	);
	$form['personal']['notice']=array(
		'#markup' => '<span class="error"><strong>'.t('Please provide the information of the student here, rather than the parent.').'</strong></span>',
	);
	if($defaults) $disabled_attributes=module_invoke_all('student_disable_modify', $defaults);
	else $disabled_attributes=array();
	if(!empty($disabled_attributes))
		$form['personal']['notice']['#markup'].='<br/><span class="error"><strong>'.
			t('You cannot modify some items of your information, because you done something related to you identify.').
			'</strong></span>';
	$form['personal']['idcard_type'] = array('#type' => 'select',
		'#title' => t('Your ID Card Type'),
		'#options' => array(
			'0' => t('Mainland ID Card'),
			'1' => t('Oversea Passport'),
		),
		'#default_value' => $defaults ? $defaults->idcard_type:'0',
		'#disabled' => in_array('idcard_type', $disabled_attributes) || in_array('idnumber', $disabled_attributes),
		'#required' => TRUE,
	);
	$form['personal']['idnumber'] = array('#type' => 'textfield',
		'#title' => t('Your ID Card Number'),
		'#description' => t('We\'re calculating gender and date of birth based on your ID card number.') ,
		'#default_value' => $defaults ? $defaults->idcard_number:'',
		'#disabled' => in_array('idnumber', $disabled_attributes),
		'#maxlength' => 18,
		'#required' => TRUE,
		'#attributes' => array('style'=>'text-transform: uppercase; ime-mode: disabled; -webkit-ime-mode: disabled;'),
	);
	$form['personal']['dateofbirth'] = array('#type' => 'date',
		'#title' => t('Your Date of Birth'),
		'#default_value' => $defaults ? array(
			'year' => substr($defaults->date_of_birth,0,4),
			'month' => 1*substr($defaults->date_of_birth,4,2),
			'day' => 1*substr($defaults->date_of_birth,6,2),
		):array(),
		'#disabled' => in_array('dateofbirth', $disabled_attributes) || in_array('idnumber', $disabled_attributes),
		'#required' => TRUE,
		'#element_validate' => array(),
		'#states' => array(
			'invisible' => array(
				':input[name="idcard_type"]' => array('value' =>'0'),
			),
			'optional' => array(
				':input[name="idcard_type"]' => array('value' =>'0'),
			)
		),
	);
	$form['personal']['gender'] = array('#type' => 'radios',
		'#title' => t('Your Gender'),
		'#default_value' => $defaults ? $defaults->gender: '1',
		'#options' => array('1'=>t('Male'), '2'=>t('Female')),
		'#disabled' => in_array('gender', $disabled_attributes) || in_array('idnumber', $disabled_attributes),
		'#required' => TRUE,
		'#states' => array(
			'invisible' => array(
				':input[name="idcard_type"]' => array('value' =>'0'),
			),
			'optional' => array(
				':input[name="idcard_type"]' => array('value' =>'0'),
			)
		),
	);
	$form['personal']['truename'] = array('#type' => 'textfield',
		'#title' => t('Your Name'),
		'#default_value' => $defaults ? $defaults->name:'',
		'#disabled' => in_array('name', $disabled_attributes),
		'#maxlength' => 50,
		'#required' => TRUE,
		'#attributes' => array('style'=>'ime-mode: enabled; -webkit-ime-mode: enabled;'),
	);

	$form['personal']['haveexname'] = array('#type' => 'checkbox',
		'#title' => t('I have exname'),
		'#default_value' => $defaults ? !empty($defaults->exname):FALSE,
		'#disabled' => in_array('name', $disabled_attributes),
		'#description' => t('If you do not have exname, please uncheck the above checkbox.'),
	);
	$form['personal']['exname'] = array('#type' => 'textfield',
		'#title' => t('Your Ex Name'),
		'#default_value' => $defaults ? $defaults->exname:'',
		'#disabled' => in_array('name', $disabled_attributes),
		'#maxlength' => 50,
		'#attributes' => array('style'=>'ime-mode: enabled; -webkit-ime-mode: enabled;'),
		'#states' => array(
			'visible' => array(
				':input[name="haveexname"]' => array('checked' =>TRUE),
			),
			'required' => array(
				':input[name="haveexname"]' => array('checked' =>TRUE),
			)
		),
	);

	$form['personal']['pyname'] = array('#type' => 'textfield',
		'#title' => t('Your Name in alphabet'),
		'#description' => t('Only Half-width alphabet is allowed.'),
		'#default_value' => $defaults ? $defaults->foreign_name:'',
		'#disabled' => in_array('name', $disabled_attributes),
		'#maxlength' => 100,
		'#required' => TRUE,
		'#attributes' => array('style'=>'text-transform: uppercase; ime-mode: disabled; -webkit-ime-mode: disabled;'),
	);
	if($defaults) {
		$form['personal']['current_photo'] = array(
			'#type' => 'item',
			'#title' => t('Current Picture'),
			'#markup' => sprintf('<img src="%s" style="padding-right: 10px"/>', $defaults->picture),
		);
	}

	$form['personal']['photo'] = array(
		'#type' => 'managed_file',
		'#title' => !$defaults?t('Photo'):t('Change Photo'),
		'#required' => !$defaults,
		'#disabled' => in_array('photo', $disabled_attributes),
		'#upload_validators' => array(
			'file_validate_size' => array( 4 * 1024 * 1024),
			'file_validate_extensions' => array('jpg png jpeg'),
			'file_validate_image_resolution' => array('200x200', '150x150'),
			'file_validate_is_image' => array(),
		),
		'#description' => t('Only image files are allowed to be uploaded.'),
	);
	if($defaults) {
		$form['personal']['photo']['#description'] .= t('If you want to change the picture, please upload it here. Otherwise, just leave it blank.');
	}
	$form['#validate'][]='student_user_account_form_validate';
	$form['#submit'][]='student_user_account_form_save';
}

function student_picture($account, $rev) {
	if(interface_exists('SaeInterface')) {
		$kv = new SaeKV();
		$kv->init();
		$fname=sprintf('student_photos_%s_%s', $account->uid, $rev);
		$img_tmp=$kv->get($fname);
		if(!$img_tmp) return NULL;
		unset($kv);
	}
	else {
		$query=db_query('SELECT photo FROM {photos} where uid=:uid AND photoid=:rev',array(':uid'=>$account->uid, ':rev'=>$rev));
		$img_tmp=$query->fetchField();
		if(!$img_tmp) return NULL;
	}
	$img=imagecreatefromstring(base64_decode($img_tmp));
	unset($img_tmp);

	drupal_add_http_header('Content-type', 'image/jpg; charset=binary', TRUE);
	drupal_add_http_header('Content-Transfer-Encoding', 'binary', TRUE);

	// Do not expire image file, because it causes overload of server :(
	// seconds, minutes, hours, days
	$expires = 60*60*24*300;
	drupal_add_http_header("Pragma", "public", TRUE);
	drupal_add_http_header("Cache-Control", "maxage=".$expires, TRUE);
	drupal_add_http_header('Expires', gmdate('D, d M Y H:i:s', time()+$expires) . ' GMT', TRUE);
	imagejpeg($img, NULL, 100);
	imagedestroy($img);
	unset($img);
}

function student_user_account_form_validate($form, $form_state) {
	$user=$form_state['user'];
	$edit=$form_state['values'];

	// 1. Validating idcard number
	$idnumber=strtoupper(trim($edit['idnumber']));
	// 1.1 If the idcard number is occupied by any others.
	$query=db_query('SELECT EXISTS( SELECT * FROM {students} WHERE idcard_number=:idcard_number AND uid<>:uid)',
		array(':idcard_number'=>$idnumber, ':uid'=>$user->uid)
	);
	if($query->fetchField())  {
		form_set_error('idnumber', t('The ID Card number you\'ve entered is occupied by somebody else.'));
		return;
	}
	else {
		// 1.2 If not occupied, then check if the number is valid
		if($edit['idcard_type']=='0') {
			// 1.2.1 Is it a valid idcard number?
			if(!_student_is_idcardn_validate($idnumber)) {
				form_set_error('idnumber', t('The ID Card number you\'ve entered is not valid.'));
				return;
			} else {
			// 1.2.2 If valid, is the date too new?
				$edit['dateofbirth']['year']=substr($idnumber,6,4);
				$edit['dateofbirth']['month']=substr($idnumber,10,2);
				$edit['dateofbirth']['day']=substr($idnumber,12,2);
			}
		} else {
			if(empty($idnumber)) {
				form_set_error('idnumber', t('!name field is required.', array('!name'=>t('Your Name'))));
			}
		}
	}
    
    $exname=trim($edit['exname']);
	if($edit['haveexname'] && empty($exname)) {
		form_set_error('exname', t('!name field is required.', array('!name'=>t('Your Ex Name'))));
	}
		

	// 2. Validating birth date
	$datestr=sprintf("%04d%02d%02d",$edit['dateofbirth']['year'], $edit['dateofbirth']['month'], $edit['dateofbirth']['day']);
	if(_student_is_date_validate($datestr)) {
		$date=new DateTime();
		$date->setDate($edit['dateofbirth']['year'], $edit['dateofbirth']['month'], $edit['dateofbirth']['day']);
		if($date >= new DateTime())
			form_set_error('dateofbirth', t('The birth date you\'ve selected is not valid.'));
	} else
		form_set_error('dateofbirth', t('The birth date you\'ve selected is not valid.'));

	// 3. Validating pyname
	if(!preg_match('/^[A-Z ]+$/', strtoupper(trim($edit['pyname'])))) {
		form_set_error('pyname', t('The alphabet name you\'ve entered is not valid.'));
	}
}

function student_user_account_form_save($form, &$form_state) {
	$user=$form_state['user'];
	db_merge('students')
		->key(array('uid' => $user->uid))
		->fields(array(
			'uid' => $user->uid,
			'idcard_type' => $form_state['values']['idcard_type'],
			'idcard_number' => strtoupper(trim($form_state['values']['idnumber'])),
			'date_of_birth' => $form_state['values']['idcard_type']=='0'?
				substr(strtoupper(trim($form_state['values']['idnumber'])), 6, 8):
				sprintf("%04d%02d%02d",$form_state['values']['dateofbirth']['year'], $form_state['values']['dateofbirth']['month'], $form_state['values']['dateofbirth']['day']),
			'gender' => $form_state['values']['idcard_type']=='0'?
				2-(substr(trim($form_state['values']['idnumber']),16,1) % 2):
				$form_state['values']['gender'],
			'name' => trim($form_state['values']['truename']),
			'exname' => $form_state['values']['haveexname']?trim($form_state['values']['exname']):'',
			'foreign_name' => strtoupper(trim($form_state['values']['pyname'])),
	))->execute();
	if($form_state['values']['photo']) {
			$file=file_load($form_state['values']['photo']);
			$image=image_load($file->uri);
			$image->info['extension']='jpeg';
			if(interface_exists('SaeInterface'))
				$newfile='saemc://'.$file->filename.'.jpg';
			else
				$newfile=$file->uri.'.jpg';
			image_save($image, $newfile);
			unset($image);
			$data=file_get_contents($newfile);
			file_unmanaged_delete($newfile);
			if(interface_exists('SaeInterface')) {
				$photoid=db_insert('photos')->fields(array(
					'uid' => $user->uid,
				))->execute();
				$kv = new SaeKV();
				$kv->init();
				$fname=sprintf('student_photos_%s_%s', $user->uid, $photoid);
				$kv->set($fname, base64_encode($data));
				unset($kv);
			} else {
				$photoid=db_insert('photos')->fields(array(
					'uid' => $user->uid,
					'photo' => base64_encode($data),
				))->execute();
			}
			unset($data);
			db_update('students')->condition('uid', $user->uid)->fields(array(
				'picture' => $photoid
			))->execute();
			$obj=db_query('SELECT * FROM {students} WHERE uid=:uid',array(':uid'=>$user->uid))->fetchObject();
			cache_set('student.'.$user->uid, $obj);
	}
	if(empty($form_state['redirect']))
		$form_state['redirect']=sprintf('user/%d', $user->uid);
	watchdog('user',
		'Modified the information of !name !truename.', array(
			'!name'=>$user->name,
			'!truename'=>trim($form_state['values']['truename'])
			),
		WATCHDOG_INFO
	);
}

function student_form_user_pass_alter(&$form, &$form_state) {
	if(user_access('administer users')) return;
	if($GLOBALS['user']->uid>=2) {
		unset($form['name']);
		unset($form['mail']);
		unset($form['actions']);
		$form['mail']=array(
			'#type'=>'item',
			'#markup'=>t('You must be logged out before resetting password.'),
		);
		$form['logout']=array(
			'#type'=>'item',
			'#markup'=>l(t('Logout and request new password'), 'user/logout', array('query' => array('destination' => 'user/password'))),
		);
		unset($form['captcha']);
		
		return;
	}

	unset($form['name']);
	unset($form['mail']);
	$form["actions"]['submit']['#value']=t('Reset password');
	$form["actions"]['submit']['#weight']=10;
	
	$form['notice'] = array(
		'#type' => 'markup',
		'#markup' => t('You\'ll have to provide following information when reseting password. ID Card Number is required here.'),
		'#weight'=>'0',
	);
	$form['idnumber'] = array(
		'#title' => t('Your ID Card Number'),
		'#type' => 'textfield',
		'#size' => '60',
		'#maxlength' => 18,
		'#weight' => 1,
		'#required' => TRUE,
	);
	$form['condselect'] = array(
		'#type' => 'radios',
		'#options' => array( '1' => t('I know the username'), '2' => t('I\'ve forgotten the username')),
		'#default_value' => '1',
		'#weight' => 2,
	);
	$form['sid'] = array(
		'#title' => t('Your username'),
		'#type' => 'textfield',
		'#size' => '60',
		'#weight' => 3,
		'#states' => array(
			'visible' => array(
				'input[name="condselect"]' => array('value' =>'1'),
			),
			'required' => array(
				'input[name="condselect"]' => array('value' =>'1'),
			)
		),
	);
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Your Name'),
		'#size' => '60',
		'#weight' => 3,
		'#states' => array(
			'visible' => array(
				'input[name="condselect"]' => array('value' =>'2'),
			),
			'required' => array(
				'input[name="condselect"]' => array('value' =>'2'),
			)
		),
	);
	$form['#validate']=array('student_form_user_pass_validate');
	$form['#submit']=array('student_form_user_pass_submit');
	drupal_set_title(t('Reset password'));
}

function student_form_user_pass_validate($form, &$form_state) {
	if($form_state['values']['condselect']==1) {
		if(trim($form_state['values']['sid']) == '') {
			form_set_error('sid', t('!name field is required.', array('!name'=>$form['sid']['#title'])));
			return;
		}
	} else {
		if(trim($form_state['values']['name']) == '') {
			form_set_error('name', t('!name field is required.', array('!name'=>$form['name']['#title'])));
			return;
		}
	}
	
	if($form_state['values']['condselect']==1) {
		$query=db_query('SELECT EXISTS( SELECT * FROM {users} u INNER JOIN {students} s ON u.uid=s.uid '.
			'WHERE u.name=:username AND s.idcard_number=:idcardnumber)',
			array(':username'=>$form_state['values']['sid'], ':idcardnumber'=>$form_state['values']['idnumber'])
		);
		if(!$query->fetchField()) {
			form_set_error('sid', t('Sorry, the username and the IDCard number do not meet our records.'));
			return;
		}
	} else {
		$query=db_query('SELECT EXISTS( SELECT * FROM {students} s WHERE s.name=:username AND s.idcard_number=:idcardnumber)',
			array(':username'=>$form_state['values']['name'], ':idcardnumber'=>$form_state['values']['idnumber'])
		);
		if(!$query->fetchField()) {
			form_set_error('name', t('Sorry, the Name and the IDCard number do not meet our records.'));
			return;
		}
	}
}

function student_form_user_pass_submit($form, &$form_state) {
	// We will detect users based on one's IDCard number and his realname.
	$query=db_query('SELECT u.uid FROM {users} u INNER JOIN {students} s ON u.uid=s.uid WHERE s.idcard_number=:idcardnumber',
		array(':idcardnumber'=>$form_state['values']['idnumber']));
	$uid=$query->fetchField();
	$account = user_load($uid);
	$newpass = user_password(6);

	user_save($account, array('pass'=>$newpass));
	
	db_delete('flood')
		->condition('identifier',$uid.'-%','LIKE')
		->execute();
	
	drupal_set_message(t('Based on your request, we\'ve reset <span class="error">!name</span>\'s password. Your new password is <span class="error"><tt>!pass</tt></span>. '.
		'Please write it down and keep it in a safe place. Or, you can change it right now.', array('!name' => $account->name, '!pass' => $newpass)));

	watchdog('user',
		'The password of !name was resetted.', array(
			'!name'=>$account->name,
			),
		WATCHDOG_INFO
	);

	// We need to fill up more information after login
	$data['uid']=user_authenticate($account->name, $newpass);
	user_login_submit(array(),$data);

	$form_state['redirect']='user/'.$account->uid.'/edit';
}


function student_user_view($user, $view_mode, $langcode) {
	$student=student_load($user);
	if(!$student) return;
	$user->content['pi'] = array(
		'#type' => 'user_profile_category',
		'#title' => t('Personal information'),
		'#weight' => '1',
	);
	$user->content['pi']['name'] = array(
		'#type' => 'user_profile_item',
		'#title' => sprintf('<img src="%s" style="padding-right: 10px" align="left" height="100"/>', $student->picture).t('Real Name'),
		'#markup' => $student->name,
	);
	$user->content['pi']['gender'] = array(
		'#type' => 'user_profile_item',
		'#title' => t('Gender'),
		'#markup' => $student->gender==1?t('Male'):t('Female'),
	);
	if(user_access('access user profiles'))
		$user->content['pi']['name']['#markup'] .= sprintf(' (%s)', 
			substr_replace($student->idcard_number, str_repeat('*', strlen($student->idcard_number)-6), 3, -3)
		);
}

function student_user_view_alter(&$build) {
	unset($build['summary']);
}

/**
 * Implementation of object_load().
 */
function student_load($user) {
	if(empty($user)) return FALSE;
	if(!is_object($user)) $user=user_load($user);
	if($user && $user->uid) {
		$obj=cache_get('student.'.$user->uid);
		if(!$obj) {
			$obj=db_query('SELECT * FROM {students} WHERE uid=:uid',array(':uid'=>$user->uid))->fetchObject();
			cache_set('student.'.$user->uid, $obj);
		}
		if(!$obj) return FALSE;
		$obj->photoid=$obj->picture;
		if(!empty($obj->picture)) {
			if(interface_exists('SaeInterface')) {
				$fname=sprintf('student_photos_%s_%s', $user->uid, $obj->photoid);
				$kv = new SaeKV();
				$kv->init();
				$obj->rawpicture=$kv->get($fname);
				unset($kv);
			} else {
				$obj->rawpicture=db_query('SELECT photo FROM {photos} WHERE uid=:uid AND photoid=:rev', array(':uid'=>$user->uid, ':rev'=>$obj->picture))->fetchField();
			}
		}
		else $obj->rawpicture=NULL;
		if(preg_match('/(?i)msie [1-8]/',$_SERVER['HTTP_USER_AGENT'])) {
			$url=sprintf('%suser/%s/%s/picture.jpg', base_path(), $obj->uid, $obj->picture,0,4);
			$obj->picture=$url;
		} else $obj->picture='data:image/jpeg;base64,'.$obj->rawpicture;
		return $obj;
	}
	else return FALSE;
}

function student_user_delete($user) {
	db_delete('photos')->condition('uid',$user->uid)->execute();
	db_delete('students')->condition('uid',$user->uid)->execute();
}
?>
